// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: payment/v1/payment.proto

package paymentv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentGateway int32

const (
	PaymentGateway_PAYMENT_GATEWAY_UNSPECIFIED PaymentGateway = 0
	PaymentGateway_PAYMENT_GATEWAY_STRIPE      PaymentGateway = 1
	PaymentGateway_PAYMENT_GATEWAY_XENDIT      PaymentGateway = 2
)

// Enum value maps for PaymentGateway.
var (
	PaymentGateway_name = map[int32]string{
		0: "PAYMENT_GATEWAY_UNSPECIFIED",
		1: "PAYMENT_GATEWAY_STRIPE",
		2: "PAYMENT_GATEWAY_XENDIT",
	}
	PaymentGateway_value = map[string]int32{
		"PAYMENT_GATEWAY_UNSPECIFIED": 0,
		"PAYMENT_GATEWAY_STRIPE":      1,
		"PAYMENT_GATEWAY_XENDIT":      2,
	}
)

func (x PaymentGateway) Enum() *PaymentGateway {
	p := new(PaymentGateway)
	*p = x
	return p
}

func (x PaymentGateway) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentGateway) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentGateway) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentGateway) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentGateway.Descriptor instead.
func (PaymentGateway) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

type CreatePaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreatePaymentIntentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentId            string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId              string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentGateway       PaymentGateway         `protobuf:"varint,5,opt,name=payment_gateway,json=paymentGateway,proto3,enum=payment.v1.PaymentGateway" json:"payment_gateway,omitempty"`
	GatewayTransactionId string                 `protobuf:"bytes,6,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	GatewayMetadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=gateway_metadata,json=gatewayMetadata,proto3" json:"gateway_metadata,omitempty"` // e.g., stripe -> { "client_secret": "...", "payment_intent_id": "pi_xx" }
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentIntentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetPaymentGateway() PaymentGateway {
	if x != nil {
		return x.PaymentGateway
	}
	return PaymentGateway_PAYMENT_GATEWAY_UNSPECIFIED
}

func (x *CreatePaymentIntentResponse) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetGatewayMetadata() *structpb.Struct {
	if x != nil {
		return x.GatewayMetadata
	}
	return nil
}

func (x *CreatePaymentIntentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreatePaymentIntentResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CreatePaymentIntentResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=payment.v1.HealthStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bbuf/validate/validate.proto\"A\n" +
	"\x1aCreatePaymentIntentRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\"\xc0\x04\n" +
	"\x1bCreatePaymentIntentResponse\x12'\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tpaymentId\x12#\n" +
	"\border_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\x12&\n" +
	"\x06amount\x18\x03 \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\x12%\n" +
	"\bcurrency\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x03R\bcurrency\x12M\n" +
	"\x0fpayment_gateway\x18\x05 \x01(\x0e2\x1a.payment.v1.PaymentGatewayB\b\xbaH\x05\x82\x01\x02\x10\x01R\x0epaymentGateway\x12@\n" +
	"\x16gateway_transaction_id\x18\x06 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x14gatewayTransactionId\x12B\n" +
	"\x10gateway_metadata\x18\a \x01(\v2\x17.google.protobuf.StructR\x0fgatewayMetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.payment.v1.HealthStatusR\x06status*i\n" +
	"\x0ePaymentGateway\x12\x1f\n" +
	"\x1bPAYMENT_GATEWAY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_GATEWAY_STRIPE\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_GATEWAY_XENDIT\x10\x02*g\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x022\xb9\x01\n" +
	"\x0ePaymentService\x12f\n" +
	"\x13CreatePaymentIntent\x12&.payment.v1.CreatePaymentIntentRequest\x1a'.payment.v1.CreatePaymentIntentResponse\x12?\n" +
	"\x06Health\x12\x19.payment.v1.HealthRequest\x1a\x1a.payment.v1.HealthResponseB\xae\x01\n" +
	"\x0ecom.payment.v1B\fPaymentProtoP\x01ZEgithub.com/raphaeldiscky/go-micro-commerce/proto/payment/v1;paymentv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Payment.V1\xca\x02\n" +
	"Payment\\V1\xe2\x02\x16Payment\\V1\\GPBMetadata\xea\x02\vPayment::V1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_v1_payment_proto_goTypes = []any{
	(PaymentGateway)(0),                 // 0: payment.v1.PaymentGateway
	(HealthStatus)(0),                   // 1: payment.v1.HealthStatus
	(*CreatePaymentIntentRequest)(nil),  // 2: payment.v1.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil), // 3: payment.v1.CreatePaymentIntentResponse
	(*HealthRequest)(nil),               // 4: payment.v1.HealthRequest
	(*HealthResponse)(nil),              // 5: payment.v1.HealthResponse
	(*structpb.Struct)(nil),             // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.CreatePaymentIntentResponse.payment_gateway:type_name -> payment.v1.PaymentGateway
	6, // 1: payment.v1.CreatePaymentIntentResponse.gateway_metadata:type_name -> google.protobuf.Struct
	7, // 2: payment.v1.CreatePaymentIntentResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: payment.v1.CreatePaymentIntentResponse.updated_at:type_name -> google.protobuf.Timestamp
	7, // 4: payment.v1.CreatePaymentIntentResponse.expires_at:type_name -> google.protobuf.Timestamp
	1, // 5: payment.v1.HealthResponse.status:type_name -> payment.v1.HealthStatus
	2, // 6: payment.v1.PaymentService.CreatePaymentIntent:input_type -> payment.v1.CreatePaymentIntentRequest
	4, // 7: payment.v1.PaymentService.Health:input_type -> payment.v1.HealthRequest
	3, // 8: payment.v1.PaymentService.CreatePaymentIntent:output_type -> payment.v1.CreatePaymentIntentResponse
	5, // 9: payment.v1.PaymentService.Health:output_type -> payment.v1.HealthResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
