// Code generated by MockGen. DO NOT EDIT.
// Source: seller_service.go
//
// Generated by this command:
//
//	mockgen -source=seller_service.go -destination=../../mocks/mock_seller_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	command "github.com/raphaeldiscky/go-ddd-template/internal/application/command"
	query "github.com/raphaeldiscky/go-ddd-template/internal/application/query"
	gomock "go.uber.org/mock/gomock"
)

// MockSellerService is a mock of SellerService interface.
type MockSellerService struct {
	ctrl     *gomock.Controller
	recorder *MockSellerServiceMockRecorder
	isgomock struct{}
}

// MockSellerServiceMockRecorder is the mock recorder for MockSellerService.
type MockSellerServiceMockRecorder struct {
	mock *MockSellerService
}

// NewMockSellerService creates a new mock instance.
func NewMockSellerService(ctrl *gomock.Controller) *MockSellerService {
	mock := &MockSellerService{ctrl: ctrl}
	mock.recorder = &MockSellerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSellerService) EXPECT() *MockSellerServiceMockRecorder {
	return m.recorder
}

// CreateSeller mocks base method.
func (m *MockSellerService) CreateSeller(sellerCommand *command.CreateSellerCommand) (*command.CreateSellerCommandResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeller", sellerCommand)
	ret0, _ := ret[0].(*command.CreateSellerCommandResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeller indicates an expected call of CreateSeller.
func (mr *MockSellerServiceMockRecorder) CreateSeller(sellerCommand any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeller", reflect.TypeOf((*MockSellerService)(nil).CreateSeller), sellerCommand)
}

// DeleteSeller mocks base method.
func (m *MockSellerService) DeleteSeller(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeller", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeller indicates an expected call of DeleteSeller.
func (mr *MockSellerServiceMockRecorder) DeleteSeller(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeller", reflect.TypeOf((*MockSellerService)(nil).DeleteSeller), id)
}

// FindAllSellers mocks base method.
func (m *MockSellerService) FindAllSellers() (*query.SellerQueryListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllSellers")
	ret0, _ := ret[0].(*query.SellerQueryListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllSellers indicates an expected call of FindAllSellers.
func (mr *MockSellerServiceMockRecorder) FindAllSellers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllSellers", reflect.TypeOf((*MockSellerService)(nil).FindAllSellers))
}

// FindSellerById mocks base method.
func (m *MockSellerService) FindSellerById(id uuid.UUID) (*query.SellerQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSellerById", id)
	ret0, _ := ret[0].(*query.SellerQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSellerById indicates an expected call of FindSellerById.
func (mr *MockSellerServiceMockRecorder) FindSellerById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSellerById", reflect.TypeOf((*MockSellerService)(nil).FindSellerById), id)
}

// UpdateSeller mocks base method.
func (m *MockSellerService) UpdateSeller(updateCommand *command.UpdateSellerCommand) (*command.UpdateSellerCommandResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeller", updateCommand)
	ret0, _ := ret[0].(*command.UpdateSellerCommandResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSeller indicates an expected call of UpdateSeller.
func (mr *MockSellerServiceMockRecorder) UpdateSeller(updateCommand any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeller", reflect.TypeOf((*MockSellerService)(nil).UpdateSeller), updateCommand)
}
