apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  labels:
    app: graphql-gateway
    tier: gateway
spec:
  type: ClusterIP
  selector:
    app: graphql-gateway
  ports:
  - name: http
    port: 4000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
