apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - ingress.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - certificate.yaml
  - dashboard-service.yaml
  - dashboard-certificate.yaml
  - dashboard-middleware.yaml
  - dashboard-httproute.yaml
