apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: product-service

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: product-service
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: go-micro-commerce

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: product-service
    newName: product-service
    newTag: latest
  - name: product-service-migrations
    newName: product-service-migrations
    newTag: latest
