// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: fulfillment.proto

package fulfillment

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_UNKNOWN     HealthStatus = 0
	HealthStatus_SERVING     HealthStatus = 1
	HealthStatus_NOT_SERVING HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_fulfillment_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{0}
}

type GetShippingCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Shipping      *Shipping              `protobuf:"bytes,2,opt,name=shipping,proto3" json:"shipping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShippingCostRequest) Reset() {
	*x = GetShippingCostRequest{}
	mi := &file_fulfillment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShippingCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingCostRequest) ProtoMessage() {}

func (x *GetShippingCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingCostRequest.ProtoReflect.Descriptor instead.
func (*GetShippingCostRequest) Descriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{0}
}

func (x *GetShippingCostRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetShippingCostRequest) GetShipping() *Shipping {
	if x != nil {
		return x.Shipping
	}
	return nil
}

type GetShippingCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShippingCost  float64                `protobuf:"fixed64,2,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShippingCostResponse) Reset() {
	*x = GetShippingCostResponse{}
	mi := &file_fulfillment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShippingCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingCostResponse) ProtoMessage() {}

func (x *GetShippingCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingCostResponse.ProtoReflect.Descriptor instead.
func (*GetShippingCostResponse) Descriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{1}
}

func (x *GetShippingCostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShippingCostResponse) GetShippingCost() float64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *GetShippingCostResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetShippingCostResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Shipping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarrierId     string                 `protobuf:"bytes,1,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	FromAddress   *FromAddress           `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     *ToAddress             `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	WeightKg      float64                `protobuf:"fixed64,4,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Dimensions    *Dimensions            `protobuf:"bytes,5,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shipping) Reset() {
	*x = Shipping{}
	mi := &file_fulfillment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipping) ProtoMessage() {}

func (x *Shipping) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipping.ProtoReflect.Descriptor instead.
func (*Shipping) Descriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{2}
}

func (x *Shipping) GetCarrierId() string {
	if x != nil {
		return x.CarrierId
	}
	return ""
}

func (x *Shipping) GetFromAddress() *FromAddress {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *Shipping) GetToAddress() *ToAddress {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *Shipping) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *Shipping) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type Dimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         float64                `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Length        float64                `protobuf:"fixed64,3,opt,name=length,proto3" json:"length,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_fulfillment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{3}
}

func (x *Dimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Dimensions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Dimensions) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Customer address
type ToAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToAddress) Reset() {
	*x = ToAddress{}
	mi := &file_fulfillment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToAddress) ProtoMessage() {}

func (x *ToAddress) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToAddress.ProtoReflect.Descriptor instead.
func (*ToAddress) Descriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{4}
}

func (x *ToAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ToAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ToAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *ToAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Warehouse address
type FromAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromAddress) Reset() {
	*x = FromAddress{}
	mi := &file_fulfillment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromAddress) ProtoMessage() {}

func (x *FromAddress) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromAddress.ProtoReflect.Descriptor instead.
func (*FromAddress) Descriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{5}
}

func (x *FromAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *FromAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FromAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *FromAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=fulfillment.HealthStatus" json:"status,omitempty"` // e.g., "SERVING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_fulfillment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_fulfillment_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

var File_fulfillment_proto protoreflect.FileDescriptor

const file_fulfillment_proto_rawDesc = "" +
	"\n" +
	"\x11fulfillment.proto\x12\vfulfillment\x1a\x1bgoogle/protobuf/empty.proto\"g\n" +
	"\x16GetShippingCostRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x121\n" +
	"\bshipping\x18\x02 \x01(\v2\x15.fulfillment.ShippingR\bshipping\"\x99\x01\n" +
	"\x17GetShippingCostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rshipping_cost\x18\x02 \x01(\x01R\fshippingCost\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xf3\x01\n" +
	"\bShipping\x12\x1d\n" +
	"\n" +
	"carrier_id\x18\x01 \x01(\tR\tcarrierId\x12;\n" +
	"\ffrom_address\x18\x02 \x01(\v2\x18.fulfillment.FromAddressR\vfromAddress\x125\n" +
	"\n" +
	"to_address\x18\x03 \x01(\v2\x16.fulfillment.ToAddressR\ttoAddress\x12\x1b\n" +
	"\tweight_kg\x18\x04 \x01(\x01R\bweightKg\x127\n" +
	"\n" +
	"dimensions\x18\x05 \x01(\v2\x17.fulfillment.DimensionsR\n" +
	"dimensions\"f\n" +
	"\n" +
	"Dimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x01R\x06height\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x01R\x06length\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\"p\n" +
	"\tToAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"r\n" +
	"\vFromAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"C\n" +
	"\x0eHealthResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.fulfillment.HealthStatusR\x06status*9\n" +
	"\fHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xb1\x01\n" +
	"\x12FulfillmentService\x12\\\n" +
	"\x0fGetShippingCost\x12#.fulfillment.GetShippingCostRequest\x1a$.fulfillment.GetShippingCostResponse\x12=\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x1b.fulfillment.HealthResponseB>Z<github.com/raphaeldiscky/go-micro-commerce/proto/fulfillmentb\x06proto3"

var (
	file_fulfillment_proto_rawDescOnce sync.Once
	file_fulfillment_proto_rawDescData []byte
)

func file_fulfillment_proto_rawDescGZIP() []byte {
	file_fulfillment_proto_rawDescOnce.Do(func() {
		file_fulfillment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fulfillment_proto_rawDesc), len(file_fulfillment_proto_rawDesc)))
	})
	return file_fulfillment_proto_rawDescData
}

var file_fulfillment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fulfillment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fulfillment_proto_goTypes = []any{
	(HealthStatus)(0),               // 0: fulfillment.HealthStatus
	(*GetShippingCostRequest)(nil),  // 1: fulfillment.GetShippingCostRequest
	(*GetShippingCostResponse)(nil), // 2: fulfillment.GetShippingCostResponse
	(*Shipping)(nil),                // 3: fulfillment.Shipping
	(*Dimensions)(nil),              // 4: fulfillment.Dimensions
	(*ToAddress)(nil),               // 5: fulfillment.ToAddress
	(*FromAddress)(nil),             // 6: fulfillment.FromAddress
	(*HealthResponse)(nil),          // 7: fulfillment.HealthResponse
	(*emptypb.Empty)(nil),           // 8: google.protobuf.Empty
}
var file_fulfillment_proto_depIdxs = []int32{
	3, // 0: fulfillment.GetShippingCostRequest.shipping:type_name -> fulfillment.Shipping
	6, // 1: fulfillment.Shipping.from_address:type_name -> fulfillment.FromAddress
	5, // 2: fulfillment.Shipping.to_address:type_name -> fulfillment.ToAddress
	4, // 3: fulfillment.Shipping.dimensions:type_name -> fulfillment.Dimensions
	0, // 4: fulfillment.HealthResponse.status:type_name -> fulfillment.HealthStatus
	1, // 5: fulfillment.FulfillmentService.GetShippingCost:input_type -> fulfillment.GetShippingCostRequest
	8, // 6: fulfillment.FulfillmentService.Health:input_type -> google.protobuf.Empty
	2, // 7: fulfillment.FulfillmentService.GetShippingCost:output_type -> fulfillment.GetShippingCostResponse
	7, // 8: fulfillment.FulfillmentService.Health:output_type -> fulfillment.HealthResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fulfillment_proto_init() }
func file_fulfillment_proto_init() {
	if File_fulfillment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fulfillment_proto_rawDesc), len(file_fulfillment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fulfillment_proto_goTypes,
		DependencyIndexes: file_fulfillment_proto_depIdxs,
		EnumInfos:         file_fulfillment_proto_enumTypes,
		MessageInfos:      file_fulfillment_proto_msgTypes,
	}.Build()
	File_fulfillment_proto = out.File
	file_fulfillment_proto_goTypes = nil
	file_fulfillment_proto_depIdxs = nil
}
