package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/google/uuid"
	"github.com/raphaeldiscky/go-micro-commerce/cart-service/graph"
	"github.com/raphaeldiscky/go-micro-commerce/cart-service/internal/mapper"
	"github.com/raphaeldiscky/go-micro-commerce/pkg/utils/echoutils"
)

// AddItemToCart is the resolver for the addItemToCart field.
func (r *mutationResolver) AddItemToCart(ctx context.Context, input graph.AddCartItemInput) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Map GraphQL input to service DTO with customer ID
	req := mapper.MapToAddCartItemRequest(input, user.UserID)

	// Add item to active cart (creates cart if doesn't exist)
	updatedCart, err := r.cartService.AddItemToActiveCart(ctx, req)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// RemoveItemFromCart is the resolver for the removeItemFromCart field.
func (r *mutationResolver) RemoveItemFromCart(ctx context.Context, itemID uuid.UUID) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Remove item from active cart
	updatedCart, err := r.cartService.RemoveItemFromActiveCart(ctx, user.UserID, itemID)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// UpdateItemQuantity is the resolver for the updateItemQuantity field.
func (r *mutationResolver) UpdateItemQuantity(ctx context.Context, itemID uuid.UUID, input graph.UpdateCartItemQuantityInput) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Update item quantity in active cart
	updatedCart, err := r.cartService.UpdateActiveCartItemQuantity(
		ctx,
		user.UserID,
		itemID,
		int64(input.Quantity),
	)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// SelectItemForCheckout is the resolver for the selectItemForCheckout field.
func (r *mutationResolver) SelectItemForCheckout(ctx context.Context, itemID uuid.UUID, input graph.SelectItemForCheckoutInput) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Select/deselect item for checkout in active cart
	updatedCart, err := r.cartService.SelectActiveCartItemForCheckout(
		ctx,
		user.UserID,
		itemID,
		input.Selected,
	)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// GetMyCart is the resolver for the getMyCart field.
func (r *queryResolver) GetMyCart(ctx context.Context) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Get user's cart
	cart, err := r.cartService.GetUserActiveCart(ctx, user.UserID)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(cart), nil
}
