package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/google/uuid"
	"github.com/raphaeldiscky/go-micro-commerce/pkg/utils/echoutils"

	"github.com/raphaeldiscky/go-micro-commerce/cart-service/graph"
	"github.com/raphaeldiscky/go-micro-commerce/cart-service/internal/mapper"
)

// AddItemToCart is the resolver for the addItemToCart field.
func (r *mutationResolver) AddItemToCart(
	ctx context.Context,
	input graph.AddCartItemInput,
) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Map GraphQL input to service DTO with customer ID
	req := mapper.MapToAddCartItemRequest(input, user.UserID)

	// Add item to active cart (creates cart if doesn't exist)
	updatedCart, err := r.cartService.AddItemToActiveCart(ctx, req)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// RemoveItemFromCart is the resolver for the removeItemFromCart field.
func (r *mutationResolver) RemoveItemFromCart(
	ctx context.Context,
	itemID uuid.UUID,
) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Get user's cart
	cart, err := r.cartService.GetCartByUserID(ctx, user.UserID)
	if err != nil {
		return nil, err
	}

	// Remove item from cart
	updatedCart, err := r.cartService.RemoveItemFromCart(ctx, cart.ID, itemID)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// UpdateItemQuantity is the resolver for the updateItemQuantity field.
func (r *mutationResolver) UpdateItemQuantity(
	ctx context.Context,
	itemID uuid.UUID,
	input graph.UpdateCartItemQuantityInput,
) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Get user's cart
	cart, err := r.cartService.GetCartByUserID(ctx, user.UserID)
	if err != nil {
		return nil, err
	}

	// Update item quantity
	updatedCart, err := r.cartService.UpdateItemQuantity(
		ctx,
		cart.ID,
		itemID,
		int64(input.Quantity),
	)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// SelectItemForCheckout is the resolver for the selectItemForCheckout field.
func (r *mutationResolver) SelectItemForCheckout(
	ctx context.Context,
	itemID uuid.UUID,
	input graph.SelectItemForCheckoutInput,
) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Get user's cart
	cart, err := r.cartService.GetCartByUserID(ctx, user.UserID)
	if err != nil {
		return nil, err
	}

	// Select/deselect item for checkout
	updatedCart, err := r.cartService.SelectItemForCheckout(ctx, cart.ID, itemID, input.Selected)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(updatedCart), nil
}

// CreateCheckoutSession is the resolver for the createCheckoutSession field.
func (r *mutationResolver) CreateCheckoutSession(
	ctx context.Context,
	input graph.CreateCheckoutSessionInput,
) (*graph.CheckoutSession, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Map GraphQL input to service DTO
	req := mapper.MapToCreateCheckoutSessionRequest(input, user.UserID)

	// Create checkout session
	session, err := r.checkoutSessionService.CreateCheckoutSession(ctx, req)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCheckoutSessionFromDTO(session), nil
}

// PlaceOrder is the resolver for the placeOrder field.
func (r *mutationResolver) PlaceOrder(
	ctx context.Context,
	sessionID uuid.UUID,
	input graph.PlaceOrderInput,
) (*graph.CheckoutSession, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Map GraphQL input to service DTO
	req := mapper.MapToPlaceOrderRequest(input, user.UserID)

	// Place order
	session, err := r.checkoutSessionService.PlaceOrder(ctx, sessionID, req)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCheckoutSessionFromDTO(session), nil
}

// CancelCheckoutSession is the resolver for the cancelCheckoutSession field.
func (r *mutationResolver) CancelCheckoutSession(
	ctx context.Context,
	sessionID uuid.UUID,
) (*graph.CheckoutSession, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Cancel checkout session
	session, err := r.checkoutSessionService.CancelCheckoutSession(ctx, sessionID, user.UserID)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCheckoutSessionFromDTO(session), nil
}

// GetMyCart is the resolver for the getMyCart field.
func (r *queryResolver) GetMyCart(ctx context.Context) (*graph.Cart, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		return nil, err
	}

	// Get user's cart
	cart, err := r.cartService.GetCartByUserID(ctx, user.UserID)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCartFromDTO(cart), nil
}

// GetCheckoutSession is the resolver for the getCheckoutSession field.
func (r *queryResolver) GetCheckoutSession(
	ctx context.Context,
	id uuid.UUID,
) (*graph.CheckoutSession, error) {
	// Get checkout session
	session, err := r.checkoutSessionService.GetCheckoutSession(ctx, id)
	if err != nil {
		return nil, err
	}

	return mapper.MapToGraphQLCheckoutSessionFromDTO(session), nil
}
