apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: api-gateway
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: api-gateway
    matchExpressions:
      - key: component
        operator: NotIn
        values:
          - migration
