apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: api-gateway
