apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway

resources:
  - ../../../base/gateway

labels:
  - pairs:
      environment: production
      app.kubernetes.io/managed-by: argocd

patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: gateway-ingress
  - path: patch-middlewares.yaml
    target:
      kind: Middleware
      name: api-cors
