apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../base/api-gateway

labels:
  - pairs:
      environment: production
      app.kubernetes.io/managed-by: argocd

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml

configMapGenerator:
  - name: api-gateway-config
    behavior: merge
    literals:
      - ENV=production
      - LOG_LEVEL=info

images:
  - name: api-gateway
    newTag: latest
