apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
