apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
