#https://taskfile.dev/#/installation
#https://github.com/go-task/task/issues/1115
version: "3"

vars:
  GOOS: "{{default OS .GOOS}}"
  DC_DIR: "deployments/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yaml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yaml"
  DEV_DC_FILE: "{{.DC_DIR}}/dev.yaml"
  GRAPHQL_GATEWAY_DC_FILE: "{{.DC_DIR}}/graphql-gateway.yaml"
  MONITORING_DC_FILE: "{{.DC_DIR}}/monitoring.yaml"
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'
  COMPOSE_FILES:
    sh: |
      echo "\
        -f {{.DC_DIR}}/postgres.yaml \
        -f {{.DC_DIR}}/redis.yaml \
        -f {{.DC_DIR}}/kafka.yaml \
        -f {{.DC_DIR}}/monitoring.yaml \
        -f {{.DC_DIR}}/vault.yaml \
        -f {{.DC_DIR}}/dev-tools.yaml \
        -f {{.DC_DIR}}/api-gateway.yaml \
        -f {{.DC_DIR}}/graphql-gateway.yaml \
        -f {{.DC_DIR}}/temporal.yaml \
        -f {{.DC_DIR}}/elasticsearch.yaml \
        -f {{.DC_DIR}}/apps.yaml \
        -f {{.DC_DIR}}/dev.yaml"

tasks:
  install_tools:
    desc: Install all dependencies for the project
    cmds:
      - sh ./scripts/install-tools.sh

  deps:
    desc: Install project dependencies
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Installing dependencies for all services..."
          bash ./scripts/install-dependencies.sh
        else
          echo "Installing dependencies for {{.SERVICE}}..."
          bash ./scripts/install-dependencies.sh {{.SERVICE}}
        fi

  build:
    desc: Build docker images
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Building docker images for all services..."
          bash ./scripts/lint.sh
          bash ./scripts/format.sh
          bash ./scripts/build.sh
        else
          echo "Building images for {{.SERVICE}}..."
          bash ./scripts/lint.sh {{.SERVICE}}
          bash ./scripts/format.sh {{.SERVICE}}
          bash ./scripts/build.sh {{.SERVICE}}
        fi
  push:
    desc: Push all services to the container registry
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Pushing all services..."
          bash ./scripts/lint.sh
          bash ./scripts/push.sh
        else
          echo "Pushing {{.SERVICE}}..."
          bash ./scripts/lint.sh {{.SERVICE}}
          bash ./scripts/push.sh {{.SERVICE}}
        fi

  migrateup:
    desc: Run database migrations
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Running migrations for all services..."
          bash ./scripts/migrate.sh up
        else
          echo "Running migrations for {{.SERVICE}}..."
          bash ./scripts/migrate.sh up {{.SERVICE}}
        fi

  migratedown:
    desc: Rollback database migrations
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Rolling back migrations for all services..."
          sh ./scripts/migrate.sh down
        else
          echo "Rolling back migrations for {{.SERVICE}}..."
          sh ./scripts/migrate.sh down {{.SERVICE}}
        fi

  run:
    desc: Run a specific service with air
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Running all services with air..."
          bash ./scripts/run.sh
        else
          echo "Running {{.SERVICE}} with air..."
          bash ./scripts/run.sh {{.SERVICE}}
        fi

  sleep:
    vars:
      DURATION: "{{default 5 .DURATION}}"
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"

  start_infra:
    desc: Start local infrastructure using docker compose
    cmds:
      - docker network create --driver bridge go-micro-commerce || true
      - docker compose -f {{.INFRA_DC_FILE}} up -d

  start_monitoring:
    desc: Start local monitoring using docker compose
    cmds:
      - docker compose -f {{.MONITORING_DC_FILE}} up -d

  start_apps:
    desc: Start all applications using docker compose
    cmds:
      - docker compose -f {{.APPS_DC_FILE}} up -d

  start_dev:
    desc: Start local development using docker compose
    cmds:
      - docker compose -f {{.DEV_DC_FILE}} up -d

  stop_infra:
    desc: Stop local infrastructure using docker compose
    cmds:
      - docker compose {{.COMPOSE_FILES}} down
      - |
        CONTAINERS=$(docker ps --filter network=go-micro-commerce -q)
        if [ -n "$CONTAINERS" ]; then
          echo "Stopping leftover containers attached to go-micro-commerce network..."
          docker rm -f $CONTAINERS
        fi
      - docker network rm go-micro-commerce

  stop_dev:
    desc: Stop local development using docker compose
    cmds:
      - docker compose -f {{.DEV_DC_FILE}} down

  stop_monitoring:
    desc: Stop local monitoring using docker compose
    cmds:
      - docker compose -f {{.MONITORING_DC_FILE}} down

  stop_apps:
    desc: Stop all applications using docker compose
    cmds:
      - docker compose -f {{.APPS_DC_FILE}} down

  restart_infra:
    desc: Restart infrastructure using docker compose
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  restart_monitoring:
    desc: Restart monitoring using docker compose
    cmds:
      - task: stop_monitoring
      - task: sleep
      - task: start_monitoring

  restart_apps:
    desc: Restart applications using docker compose
    cmds:
      - task: stop_apps
      - task: sleep
      - task: start_apps

  test_file:
    desc: Run individual test file
    vars:
      FILE: "{{.FILE}}"
      TEST_TYPE: '{{default "unit" .TEST_TYPE}}'
    cmds:
      - bash ./scripts/test_file.sh {{.FILE}} {{.TEST_TYPE}}

  test_monitoring:
    desc: Run monitoring tests
    cmds:
      - bash ./scripts/test-monitoring.sh

  test:
    desc: Run unit tests
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Running unit tests for all services..."
          bash ./scripts/test.sh
        else
          echo "Running unit tests for {{.SERVICE}}..."
          bash ./scripts/test.sh {{.SERVICE}}
        fi

  format:
    desc: Run formatters
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Running formatters for all services..."
          bash ./scripts/format.sh
        else
          echo "Formatting {{.SERVICE}}..."
          bash ./scripts/format.sh {{.SERVICE}}
        fi

  lint:
    desc: Run formatters and linters
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Running linters for all services..."
          bash ./scripts/lint.sh
        else
          echo "Running linters for {{.SERVICE}}..."
          bash ./scripts/lint.sh {{.SERVICE}}
        fi
    deps: ["format"]

  lint_sql:
    desc: Run SQL linters
    cmds:
      - sqlfluff lint

  deadcode:
    desc: Check deadcode
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Running deadcode for all services..."
          bash ./scripts/deadcode.sh
        else
          echo "Running deadcode for {{.SERVICE}}..."
          bash ./scripts/deadcode.sh {{.SERVICE}}
        fi
    deps: ["format"]

  check:
    desc: Run deadcode, linter, and formatter checks for all services
    cmds:
      - task: format
      - task: lint

  security:
    desc: Check security
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Running security for all services..."
          bash ./scripts/security.sh
        else
          echo "Running security for {{.SERVICE}}..."
          bash ./scripts/security.sh {{.SERVICE}}
        fi

  mock:
    desc: Generate mock
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Generating mocks for all services..."
          sh ./scripts/mock.sh
        else
          echo "Generating mocks for {{.SERVICE}}..."
          sh ./scripts/mock.sh {{.SERVICE}}
        fi

  proto:
    desc: Generate protobuf files
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - buf generate

  oapi:
    desc: Generate OpenAPI files
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Generating OpenAPI files for all services..."
          bash ./scripts/oapi.sh
        else
          echo "Generating OpenAPI files for {{.SERVICE}}..."
          bash ./scripts/oapi.sh {{.SERVICE}}
        fi

  graphql:
    desc: Generate GraphQL files
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Generating GraphQL files for all services..."
          bash ./scripts/graphql.sh
        else
          echo "Generating GraphQL files for {{.SERVICE}}..."
          bash ./scripts/graphql.sh {{.SERVICE}}
        fi
      - task: deps

  supergraph:
    desc: Compose Apollo Federation supergraph schema and generate frontend code
    cmds:
      - task: graphql
      - bash ./scripts/compose-supergraph.sh
      - cd frontend && pnpm codegen
      - task: deps
      - task: lint

  start_graphql_gateway:
    desc: Start GraphQL Gateway
    cmds:
      - task: supergraph
      - bash ./scripts/build.sh --no-cache graphql-gateway
      - docker compose -f {{.INFRA_DC_FILE}} up -d --force-recreate graphql-gateway graphql-gateway-consul-sidecar

  stop_graphql_gateway:
    desc: Stop GraphQL Gateway
    cmds:
      - docker compose -f {{.INFRA_DC_FILE}} stop graphql-gateway graphql-gateway-consul-sidecar
      - docker compose -f {{.INFRA_DC_FILE}} rm -f graphql-gateway graphql-gateway-consul-sidecar

  restart_graphql_gateway:
    desc: Restart GraphQL Gateway
    cmds:
      - task: stop_graphql_gateway
      - task: sleep
      - task: start_graphql_gateway

  sqlc:
    desc: Generate SQLC files
    vars:
      SERVICE: '{{.SERVICE | default ""}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Generating SQLC files for all services..."
          sh ./scripts/sqlc.sh
        else
          echo "Generating SQLC files for {{.SERVICE}}..."
          sh ./scripts/sqlc.sh {{.SERVICE}}
        fi

  uuid:
    desc: Generate UUID
    cmds:
      - bash ./scripts/uuid.sh
