apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - ../../../base/payment-service

labels:
  - pairs:
      environment: production
      app.kubernetes.io/managed-by: argocd

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
  - path: patch-hpa.yaml
  - path: patch-image-pull-secrets.yaml

configMapGenerator:
  - name: payment-service-config
    behavior: merge
    literals:
      - APP_ENVIRONMENT=production
      - ENV=production
      - LOG_LEVEL=info

images:
  - name: ghcr.io/raphaeldiscky/go-micro-commerce/payment-service
    newTag: v0.0.0
