apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - ../../../base/chat-service

labels:
  - pairs:
      environment: production
      app.kubernetes.io/managed-by: argocd

components:
  - ../_common

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
  - path: patch-hpa.yaml

configMapGenerator:
  - name: chat-service-config
    behavior: merge
    literals:
      - APP_ENVIRONMENT=production
      - ENV=production
      - LOG_LEVEL=info

images:
  - name: ghcr.io/raphaeldiscky/go-micro-commerce/chat-service
    newTag: 0.1.5
