apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: chat-service
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
