// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: chat/connection/v1/connection.proto

package connectionv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserType represents the type of user in the chat system
type UserType int32

const (
	UserType_USER_TYPE_UNSPECIFIED UserType = 0
	UserType_USER_TYPE_USER        UserType = 1 // Regular user/customer
	UserType_USER_TYPE_ADMIN       UserType = 2 // Admin/support agent
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER_TYPE_UNSPECIFIED",
		1: "USER_TYPE_USER",
		2: "USER_TYPE_ADMIN",
	}
	UserType_value = map[string]int32{
		"USER_TYPE_UNSPECIFIED": 0,
		"USER_TYPE_USER":        1,
		"USER_TYPE_ADMIN":       2,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_connection_v1_connection_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_chat_connection_v1_connection_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{0}
}

// RequestConnectionRequest represents the request to establish a WebSocket connection
type RequestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgent     string                 `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestConnectionRequest) Reset() {
	*x = RequestConnectionRequest{}
	mi := &file_chat_connection_v1_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConnectionRequest) ProtoMessage() {}

func (x *RequestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_connection_v1_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConnectionRequest.ProtoReflect.Descriptor instead.
func (*RequestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{0}
}

func (x *RequestConnectionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestConnectionRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// RequestConnectionResponse represents the response for connection establishment
type RequestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddress   string                 `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Ticket        string                 `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      UserType               `protobuf:"varint,5,opt,name=user_type,json=userType,proto3,enum=chat.connection.v1.UserType" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestConnectionResponse) Reset() {
	*x = RequestConnectionResponse{}
	mi := &file_chat_connection_v1_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConnectionResponse) ProtoMessage() {}

func (x *RequestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_connection_v1_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConnectionResponse.ProtoReflect.Descriptor instead.
func (*RequestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{1}
}

func (x *RequestConnectionResponse) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *RequestConnectionResponse) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *RequestConnectionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RequestConnectionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestConnectionResponse) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

// ValidateTicketRequest represents the request to validate a connection ticket
type ValidateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketRequest) Reset() {
	*x = ValidateTicketRequest{}
	mi := &file_chat_connection_v1_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketRequest) ProtoMessage() {}

func (x *ValidateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_connection_v1_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketRequest.ProtoReflect.Descriptor instead.
func (*ValidateTicketRequest) Descriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTicketRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

// ValidateTicketResponse represents the response for ticket validation
type ValidateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      UserType               `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=chat.connection.v1.UserType" json:"user_type,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsValid       bool                   `protobuf:"varint,4,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketResponse) Reset() {
	*x = ValidateTicketResponse{}
	mi := &file_chat_connection_v1_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketResponse) ProtoMessage() {}

func (x *ValidateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_connection_v1_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketResponse.ProtoReflect.Descriptor instead.
func (*ValidateTicketResponse) Descriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTicketResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTicketResponse) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

func (x *ValidateTicketResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ValidateTicketResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// GetNodeHealthRequest represents the request to get node health status
type GetNodeHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHealthRequest) Reset() {
	*x = GetNodeHealthRequest{}
	mi := &file_chat_connection_v1_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHealthRequest) ProtoMessage() {}

func (x *GetNodeHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_connection_v1_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHealthRequest.ProtoReflect.Descriptor instead.
func (*GetNodeHealthRequest) Descriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{4}
}

// GetNodeHealthResponse represents the response for node health status
type GetNodeHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeHealth          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHealthResponse) Reset() {
	*x = GetNodeHealthResponse{}
	mi := &file_chat_connection_v1_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHealthResponse) ProtoMessage() {}

func (x *GetNodeHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_connection_v1_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHealthResponse.ProtoReflect.Descriptor instead.
func (*GetNodeHealthResponse) Descriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeHealthResponse) GetNodes() []*NodeHealth {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetNodeHealthResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// NodeHealth represents the health status of a chat node
type NodeHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Connections    int32                  `protobuf:"varint,4,opt,name=connections,proto3" json:"connections,omitempty"`
	MaxConnections int32                  `protobuf:"varint,5,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeHealth) Reset() {
	*x = NodeHealth{}
	mi := &file_chat_connection_v1_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealth) ProtoMessage() {}

func (x *NodeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_chat_connection_v1_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealth.ProtoReflect.Descriptor instead.
func (*NodeHealth) Descriptor() ([]byte, []int) {
	return file_chat_connection_v1_connection_proto_rawDescGZIP(), []int{6}
}

func (x *NodeHealth) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHealth) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeHealth) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *NodeHealth) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *NodeHealth) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

var File_chat_connection_v1_connection_proto protoreflect.FileDescriptor

const file_chat_connection_v1_connection_proto_rawDesc = "" +
	"\n" +
	"#chat/connection/v1/connection.proto\x12\x12chat.connection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"i\n" +
	"\x18RequestConnectionRequest\x12'\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tuserAgent\x12$\n" +
	"\tclient_ip\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18-R\bclientIp\"\x84\x02\n" +
	"\x19RequestConnectionResponse\x12-\n" +
	"\fnode_address\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vnodeAddress\x12\x1f\n" +
	"\x06ticket\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06ticket\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\auser_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x129\n" +
	"\tuser_type\x18\x05 \x01(\x0e2\x1c.chat.connection.v1.UserTypeR\buserType\"8\n" +
	"\x15ValidateTicketRequest\x12\x1f\n" +
	"\x06ticket\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06ticket\"\xcc\x01\n" +
	"\x16ValidateTicketResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x129\n" +
	"\tuser_type\x18\x02 \x01(\x0e2\x1c.chat.connection.v1.UserTypeR\buserType\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x19\n" +
	"\bis_valid\x18\x04 \x01(\bR\aisValid\"\x16\n" +
	"\x14GetNodeHealthRequest\"c\n" +
	"\x15GetNodeHealthResponse\x124\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1e.chat.connection.v1.NodeHealthR\x05nodes\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x90\x02\n" +
	"\n" +
	"NodeHealth\x12#\n" +
	"\anode_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x06nodeId\x12$\n" +
	"\aaddress\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\aaddress\x12!\n" +
	"\x06status\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x06status\x12)\n" +
	"\vconnections\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\vconnections\x120\n" +
	"\x0fmax_connections\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x0emaxConnections\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen*N\n" +
	"\bUserType\x12\x19\n" +
	"\x15USER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_TYPE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_TYPE_ADMIN\x10\x022\xd4\x02\n" +
	"\x11ConnectionService\x12p\n" +
	"\x11RequestConnection\x12,.chat.connection.v1.RequestConnectionRequest\x1a-.chat.connection.v1.RequestConnectionResponse\x12g\n" +
	"\x0eValidateTicket\x12).chat.connection.v1.ValidateTicketRequest\x1a*.chat.connection.v1.ValidateTicketResponse\x12d\n" +
	"\rGetNodeHealth\x12(.chat.connection.v1.GetNodeHealthRequest\x1a).chat.connection.v1.GetNodeHealthResponseB\xe5\x01\n" +
	"\x16com.chat.connection.v1B\x0fConnectionProtoP\x01ZPgithub.com/raphaeldiscky/go-micro-commerce/proto/chat/connection/v1;connectionv1\xa2\x02\x03CCX\xaa\x02\x12Chat.Connection.V1\xca\x02\x12Chat\\Connection\\V1\xe2\x02\x1eChat\\Connection\\V1\\GPBMetadata\xea\x02\x14Chat::Connection::V1b\x06proto3"

var (
	file_chat_connection_v1_connection_proto_rawDescOnce sync.Once
	file_chat_connection_v1_connection_proto_rawDescData []byte
)

func file_chat_connection_v1_connection_proto_rawDescGZIP() []byte {
	file_chat_connection_v1_connection_proto_rawDescOnce.Do(func() {
		file_chat_connection_v1_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_connection_v1_connection_proto_rawDesc), len(file_chat_connection_v1_connection_proto_rawDesc)))
	})
	return file_chat_connection_v1_connection_proto_rawDescData
}

var file_chat_connection_v1_connection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_connection_v1_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chat_connection_v1_connection_proto_goTypes = []any{
	(UserType)(0),                     // 0: chat.connection.v1.UserType
	(*RequestConnectionRequest)(nil),  // 1: chat.connection.v1.RequestConnectionRequest
	(*RequestConnectionResponse)(nil), // 2: chat.connection.v1.RequestConnectionResponse
	(*ValidateTicketRequest)(nil),     // 3: chat.connection.v1.ValidateTicketRequest
	(*ValidateTicketResponse)(nil),    // 4: chat.connection.v1.ValidateTicketResponse
	(*GetNodeHealthRequest)(nil),      // 5: chat.connection.v1.GetNodeHealthRequest
	(*GetNodeHealthResponse)(nil),     // 6: chat.connection.v1.GetNodeHealthResponse
	(*NodeHealth)(nil),                // 7: chat.connection.v1.NodeHealth
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_chat_connection_v1_connection_proto_depIdxs = []int32{
	8, // 0: chat.connection.v1.RequestConnectionResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: chat.connection.v1.RequestConnectionResponse.user_type:type_name -> chat.connection.v1.UserType
	0, // 2: chat.connection.v1.ValidateTicketResponse.user_type:type_name -> chat.connection.v1.UserType
	8, // 3: chat.connection.v1.ValidateTicketResponse.expires_at:type_name -> google.protobuf.Timestamp
	7, // 4: chat.connection.v1.GetNodeHealthResponse.nodes:type_name -> chat.connection.v1.NodeHealth
	8, // 5: chat.connection.v1.NodeHealth.last_seen:type_name -> google.protobuf.Timestamp
	1, // 6: chat.connection.v1.ConnectionService.RequestConnection:input_type -> chat.connection.v1.RequestConnectionRequest
	3, // 7: chat.connection.v1.ConnectionService.ValidateTicket:input_type -> chat.connection.v1.ValidateTicketRequest
	5, // 8: chat.connection.v1.ConnectionService.GetNodeHealth:input_type -> chat.connection.v1.GetNodeHealthRequest
	2, // 9: chat.connection.v1.ConnectionService.RequestConnection:output_type -> chat.connection.v1.RequestConnectionResponse
	4, // 10: chat.connection.v1.ConnectionService.ValidateTicket:output_type -> chat.connection.v1.ValidateTicketResponse
	6, // 11: chat.connection.v1.ConnectionService.GetNodeHealth:output_type -> chat.connection.v1.GetNodeHealthResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_chat_connection_v1_connection_proto_init() }
func file_chat_connection_v1_connection_proto_init() {
	if File_chat_connection_v1_connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_connection_v1_connection_proto_rawDesc), len(file_chat_connection_v1_connection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_connection_v1_connection_proto_goTypes,
		DependencyIndexes: file_chat_connection_v1_connection_proto_depIdxs,
		EnumInfos:         file_chat_connection_v1_connection_proto_enumTypes,
		MessageInfos:      file_chat_connection_v1_connection_proto_msgTypes,
	}.Build()
	File_chat_connection_v1_connection_proto = out.File
	file_chat_connection_v1_connection_proto_goTypes = nil
	file_chat_connection_v1_connection_proto_depIdxs = nil
}
