// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: cart/v1/cart.proto

package cartv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED  Status = 0
	Status_STATUS_PENDING      Status = 1
	Status_STATUS_ORDER_PLACED Status = 2
	Status_STATUS_CANCELED     Status = 3
	Status_STATUS_EXPIRED      Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_ORDER_PLACED",
		3: "STATUS_CANCELED",
		4: "STATUS_EXPIRED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"STATUS_PENDING":      1,
		"STATUS_ORDER_PLACED": 2,
		"STATUS_CANCELED":     3,
		"STATUS_EXPIRED":      4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cart_v1_cart_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cart_v1_cart_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cart_v1_cart_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_cart_v1_cart_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

type GetCheckoutSessionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckoutSessionId string                 `protobuf:"bytes,1,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCheckoutSessionRequest) Reset() {
	*x = GetCheckoutSessionRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutSessionRequest) ProtoMessage() {}

func (x *GetCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*GetCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCheckoutSessionRequest) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

type GetCheckoutSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckoutSessionId string                 `protobuf:"bytes,1,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CustomerId        string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CartId            string                 `protobuf:"bytes,4,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Status            Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=cart.v1.Status" json:"status,omitempty"`
	Destination       *Destination           `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Origin            *Origin                `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	Courier           *Courier               `protobuf:"bytes,8,opt,name=courier,proto3" json:"courier,omitempty"`
	Package           *Package               `protobuf:"bytes,9,opt,name=package,proto3" json:"package,omitempty"`
	Currency          string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCheckoutSessionResponse) Reset() {
	*x = GetCheckoutSessionResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutSessionResponse) ProtoMessage() {}

func (x *GetCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*GetCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *GetCheckoutSessionResponse) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

func (x *GetCheckoutSessionResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *GetCheckoutSessionResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetCheckoutSessionResponse) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *GetCheckoutSessionResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *GetCheckoutSessionResponse) GetDestination() *Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *GetCheckoutSessionResponse) GetOrigin() *Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *GetCheckoutSessionResponse) GetCourier() *Courier {
	if x != nil {
		return x.Courier
	}
	return nil
}

func (x *GetCheckoutSessionResponse) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *GetCheckoutSessionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetCheckoutSessionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetCheckoutSessionResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetCheckoutSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *Destination) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Destination) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Destination) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Destination) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type Origin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Origin) Reset() {
	*x = Origin{}
	mi := &file_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

func (x *Origin) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Origin) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Origin) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Origin) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type Courier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Courier) Reset() {
	*x = Courier{}
	mi := &file_cart_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Courier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courier) ProtoMessage() {}

func (x *Courier) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courier.ProtoReflect.Descriptor instead.
func (*Courier) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *Courier) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      string                 `protobuf:"bytes,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Length        string                 `protobuf:"bytes,2,opt,name=length,proto3" json:"length,omitempty"`
	Width         string                 `protobuf:"bytes,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        string                 `protobuf:"bytes,4,opt,name=height,proto3" json:"height,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_cart_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *Package) GetWeightKg() string {
	if x != nil {
		return x.WeightKg
	}
	return ""
}

func (x *Package) GetLength() string {
	if x != nil {
		return x.Length
	}
	return ""
}

func (x *Package) GetWidth() string {
	if x != nil {
		return x.Width
	}
	return ""
}

func (x *Package) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *Package) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=cart.v1.HealthStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

var File_cart_v1_cart_proto protoreflect.FileDescriptor

const file_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x12cart/v1/cart.proto\x12\acart.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"U\n" +
	"\x19GetCheckoutSessionRequest\x128\n" +
	"\x13checkout_session_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x11checkoutSessionId\"\x9b\x05\n" +
	"\x1aGetCheckoutSessionResponse\x128\n" +
	"\x13checkout_session_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x11checkoutSessionId\x121\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eidempotencyKey\x12)\n" +
	"\vcustomer_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"customerId\x12!\n" +
	"\acart_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06cartId\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0f.cart.v1.StatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06status\x126\n" +
	"\vdestination\x18\x06 \x01(\v2\x14.cart.v1.DestinationR\vdestination\x12'\n" +
	"\x06origin\x18\a \x01(\v2\x0f.cart.v1.OriginR\x06origin\x12*\n" +
	"\acourier\x18\b \x01(\v2\x10.cart.v1.CourierR\acourier\x12*\n" +
	"\apackage\x18\t \x01(\v2\x10.cart.v1.PackageR\apackage\x12%\n" +
	"\bcurrency\x18\n" +
	" \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x03R\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xab\x01\n" +
	"\vDestination\x12\x1e\n" +
	"\x04city\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04city\x12 \n" +
	"\x05state\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05state\x12+\n" +
	"\vpostal_code\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\n" +
	"postalCode\x12-\n" +
	"\fcountry_code\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vcountryCode\"\xa6\x01\n" +
	"\x06Origin\x12\x1e\n" +
	"\x04city\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04city\x12 \n" +
	"\x05state\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05state\x12+\n" +
	"\vpostal_code\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\n" +
	"postalCode\x12-\n" +
	"\fcountry_code\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vcountryCode\"2\n" +
	"\aCourier\x12'\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tcourierId\"\x8c\x02\n" +
	"\aPackage\x12;\n" +
	"\tweight_kg\x18\x01 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,2})?$R\bweightKg\x126\n" +
	"\x06length\x18\x02 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,2})?$R\x06length\x124\n" +
	"\x05width\x18\x03 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,2})?$R\x05width\x126\n" +
	"\x06height\x18\x04 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,2})?$R\x06height\x12\x1e\n" +
	"\x04unit\x18\x05 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04unit\"\x0f\n" +
	"\rHealthRequest\"?\n" +
	"\x0eHealthResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.cart.v1.HealthStatusR\x06status*v\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13STATUS_ORDER_PLACED\x10\x02\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_EXPIRED\x10\x04*g\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x022\xa7\x01\n" +
	"\vCartService\x12]\n" +
	"\x12GetCheckoutSession\x12\".cart.v1.GetCheckoutSessionRequest\x1a#.cart.v1.GetCheckoutSessionResponse\x129\n" +
	"\x06Health\x12\x16.cart.v1.HealthRequest\x1a\x17.cart.v1.HealthResponseB\x96\x01\n" +
	"\vcom.cart.v1B\tCartProtoP\x01Z?github.com/raphaeldiscky/go-micro-commerce/proto/cart/v1;cartv1\xa2\x02\x03CXX\xaa\x02\aCart.V1\xca\x02\aCart\\V1\xe2\x02\x13Cart\\V1\\GPBMetadata\xea\x02\bCart::V1b\x06proto3"

var (
	file_cart_v1_cart_proto_rawDescOnce sync.Once
	file_cart_v1_cart_proto_rawDescData []byte
)

func file_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)))
	})
	return file_cart_v1_cart_proto_rawDescData
}

var file_cart_v1_cart_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cart_v1_cart_proto_goTypes = []any{
	(Status)(0),                        // 0: cart.v1.Status
	(HealthStatus)(0),                  // 1: cart.v1.HealthStatus
	(*GetCheckoutSessionRequest)(nil),  // 2: cart.v1.GetCheckoutSessionRequest
	(*GetCheckoutSessionResponse)(nil), // 3: cart.v1.GetCheckoutSessionResponse
	(*Destination)(nil),                // 4: cart.v1.Destination
	(*Origin)(nil),                     // 5: cart.v1.Origin
	(*Courier)(nil),                    // 6: cart.v1.Courier
	(*Package)(nil),                    // 7: cart.v1.Package
	(*HealthRequest)(nil),              // 8: cart.v1.HealthRequest
	(*HealthResponse)(nil),             // 9: cart.v1.HealthResponse
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_cart_v1_cart_proto_depIdxs = []int32{
	0,  // 0: cart.v1.GetCheckoutSessionResponse.status:type_name -> cart.v1.Status
	4,  // 1: cart.v1.GetCheckoutSessionResponse.destination:type_name -> cart.v1.Destination
	5,  // 2: cart.v1.GetCheckoutSessionResponse.origin:type_name -> cart.v1.Origin
	6,  // 3: cart.v1.GetCheckoutSessionResponse.courier:type_name -> cart.v1.Courier
	7,  // 4: cart.v1.GetCheckoutSessionResponse.package:type_name -> cart.v1.Package
	10, // 5: cart.v1.GetCheckoutSessionResponse.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: cart.v1.GetCheckoutSessionResponse.updated_at:type_name -> google.protobuf.Timestamp
	10, // 7: cart.v1.GetCheckoutSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 8: cart.v1.HealthResponse.status:type_name -> cart.v1.HealthStatus
	2,  // 9: cart.v1.CartService.GetCheckoutSession:input_type -> cart.v1.GetCheckoutSessionRequest
	8,  // 10: cart.v1.CartService.Health:input_type -> cart.v1.HealthRequest
	3,  // 11: cart.v1.CartService.GetCheckoutSession:output_type -> cart.v1.GetCheckoutSessionResponse
	9,  // 12: cart.v1.CartService.Health:output_type -> cart.v1.HealthResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cart_v1_cart_proto_init() }
func file_cart_v1_cart_proto_init() {
	if File_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_cart_v1_cart_proto_depIdxs,
		EnumInfos:         file_cart_v1_cart_proto_enumTypes,
		MessageInfos:      file_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_cart_v1_cart_proto = out.File
	file_cart_v1_cart_proto_goTypes = nil
	file_cart_v1_cart_proto_depIdxs = nil
}
