// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/constant"
)

type ConversationEvent interface {
	IsConversationEvent()
}

type UserEvent interface {
	IsUserEvent()
}

type ChatConnection struct {
	NodeAddress string    `json:"nodeAddress"`
	UserID      uuid.UUID `json:"userId"`
	UserType    string    `json:"userType"`
}

type Conversation struct {
	ID               uuid.UUID                   `json:"id"`
	Subject          *string                     `json:"subject,omitempty"`
	Status           constant.ConversationStatus `json:"status"`
	Priority         int                         `json:"priority"`
	Participants     []*Participant              `json:"participants"`
	ParticipantCount int                         `json:"participantCount"`
	Messages         *MessageConnection          `json:"messages"`
	CreatedAt        time.Time                   `json:"createdAt"`
	UpdatedAt        time.Time                   `json:"updatedAt"`
	EndedAt          *time.Time                  `json:"endedAt,omitempty"`
}

func (Conversation) IsEntity() {}

type CreateConversationInput struct {
	Subject        *string `json:"subject,omitempty"`
	Priority       int     `json:"priority"`
	InitialMessage *string `json:"initialMessage,omitempty"`
}

type DeliveryReceipt struct {
	MessageID      uuid.UUID `json:"messageId"`
	ConversationID uuid.UUID `json:"conversationId"`
	RecipientID    uuid.UUID `json:"recipientId"`
	DeliveredAt    time.Time `json:"deliveredAt"`
}

func (DeliveryReceipt) IsConversationEvent() {}

type JoinConversationInput struct {
	ConversationID uuid.UUID                `json:"conversationId"`
	Role           constant.ParticipantRole `json:"role"`
}

type Message struct {
	ID             uuid.UUID            `json:"id"`
	ConversationID uuid.UUID            `json:"conversationId"`
	Conversation   *Conversation        `json:"conversation"`
	SenderID       *uuid.UUID           `json:"senderId,omitempty"`
	Sender         *User                `json:"sender,omitempty"`
	Content        string               `json:"content"`
	MessageType    constant.MessageType `json:"messageType"`
	IsSystem       bool                 `json:"isSystem"`
	CreatedAt      time.Time            `json:"createdAt"`
}

func (Message) IsEntity() {}

type MessageConnection struct {
	Edges    []*MessageEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type MessageEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Message `json:"node"`
}

type Mutation struct {
}

type NewMessage struct {
	ID             uuid.UUID            `json:"id"`
	ConversationID uuid.UUID            `json:"conversationId"`
	SenderID       uuid.UUID            `json:"senderId"`
	Content        string               `json:"content"`
	MessageType    constant.MessageType `json:"messageType"`
	IsSystem       bool                 `json:"isSystem"`
	CreatedAt      time.Time            `json:"createdAt"`
}

func (NewMessage) IsConversationEvent() {}

type OnlineStatus struct {
	IsOnline bool       `json:"isOnline"`
	LastSeen *time.Time `json:"lastSeen,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Participant struct {
	ID             uuid.UUID                `json:"id"`
	ConversationID uuid.UUID                `json:"conversationId"`
	Conversation   *Conversation            `json:"conversation"`
	UserID         uuid.UUID                `json:"userId"`
	User           *User                    `json:"user"`
	UserType       constant.UserType        `json:"userType"`
	Role           constant.ParticipantRole `json:"role"`
	JoinedAt       time.Time                `json:"joinedAt"`
	LeftAt         *time.Time               `json:"leftAt,omitempty"`
	IsActive       bool                     `json:"isActive"`
}

type PresenceUpdate struct {
	UserID   uuid.UUID               `json:"userId"`
	Status   constant.PresenceStatus `json:"status"`
	LastSeen *time.Time              `json:"lastSeen,omitempty"`
}

func (PresenceUpdate) IsUserEvent() {}

type Query struct {
}

type ReadReceipt struct {
	MessageID      uuid.UUID `json:"messageId"`
	ConversationID uuid.UUID `json:"conversationId"`
	ReaderID       uuid.UUID `json:"readerId"`
	ReadAt         time.Time `json:"readAt"`
}

func (ReadReceipt) IsConversationEvent() {}

type SendDeliveryReceiptInput struct {
	MessageID      uuid.UUID `json:"messageId"`
	ConversationID uuid.UUID `json:"conversationId"`
}

type SendMessageInput struct {
	ConversationID uuid.UUID             `json:"conversationId"`
	Content        string                `json:"content"`
	MessageType    *constant.MessageType `json:"messageType,omitempty"`
	ReplyToID      *uuid.UUID            `json:"replyToId,omitempty"`
}

type SendReadReceiptInput struct {
	MessageID      uuid.UUID `json:"messageId"`
	ConversationID uuid.UUID `json:"conversationId"`
}

type Subscription struct {
}

type TypingIndicator struct {
	UserID         uuid.UUID `json:"userId"`
	ConversationID uuid.UUID `json:"conversationId"`
	IsTyping       bool      `json:"isTyping"`
	Timestamp      time.Time `json:"timestamp"`
}

func (TypingIndicator) IsConversationEvent() {}

type TypingIndicatorInput struct {
	ConversationID uuid.UUID `json:"conversationId"`
	IsTyping       bool      `json:"isTyping"`
}

type User struct {
	ID            uuid.UUID       `json:"id"`
	Conversations []*Conversation `json:"conversations"`
	OnlineStatus  *OnlineStatus   `json:"onlineStatus,omitempty"`
}

func (User) IsEntity() {}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
