// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chat/message/v1/message.proto

package messagev1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/raphaeldiscky/go-micro-commerce/proto/chat/message/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MessageServiceName is the fully-qualified name of the MessageService service.
	MessageServiceName = "chat.message.v1.MessageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MessageServiceGetMessagesProcedure is the fully-qualified name of the MessageService's
	// GetMessages RPC.
	MessageServiceGetMessagesProcedure = "/chat.message.v1.MessageService/GetMessages"
	// MessageServiceGetMessageProcedure is the fully-qualified name of the MessageService's GetMessage
	// RPC.
	MessageServiceGetMessageProcedure = "/chat.message.v1.MessageService/GetMessage"
)

// MessageServiceClient is a client for the chat.message.v1.MessageService service.
type MessageServiceClient interface {
	// GetMessages retrieves messages from a conversation with pagination
	GetMessages(context.Context, *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error)
	// GetMessage retrieves a single message by ID
	GetMessage(context.Context, *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error)
}

// NewMessageServiceClient constructs a client for the chat.message.v1.MessageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	messageServiceMethods := v1.File_chat_message_v1_message_proto.Services().ByName("MessageService").Methods()
	return &messageServiceClient{
		getMessages: connect.NewClient[v1.GetMessagesRequest, v1.GetMessagesResponse](
			httpClient,
			baseURL+MessageServiceGetMessagesProcedure,
			connect.WithSchema(messageServiceMethods.ByName("GetMessages")),
			connect.WithClientOptions(opts...),
		),
		getMessage: connect.NewClient[v1.GetMessageRequest, v1.GetMessageResponse](
			httpClient,
			baseURL+MessageServiceGetMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("GetMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// messageServiceClient implements MessageServiceClient.
type messageServiceClient struct {
	getMessages *connect.Client[v1.GetMessagesRequest, v1.GetMessagesResponse]
	getMessage  *connect.Client[v1.GetMessageRequest, v1.GetMessageResponse]
}

// GetMessages calls chat.message.v1.MessageService.GetMessages.
func (c *messageServiceClient) GetMessages(ctx context.Context, req *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error) {
	return c.getMessages.CallUnary(ctx, req)
}

// GetMessage calls chat.message.v1.MessageService.GetMessage.
func (c *messageServiceClient) GetMessage(ctx context.Context, req *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error) {
	return c.getMessage.CallUnary(ctx, req)
}

// MessageServiceHandler is an implementation of the chat.message.v1.MessageService service.
type MessageServiceHandler interface {
	// GetMessages retrieves messages from a conversation with pagination
	GetMessages(context.Context, *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error)
	// GetMessage retrieves a single message by ID
	GetMessage(context.Context, *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error)
}

// NewMessageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMessageServiceHandler(svc MessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	messageServiceMethods := v1.File_chat_message_v1_message_proto.Services().ByName("MessageService").Methods()
	messageServiceGetMessagesHandler := connect.NewUnaryHandler(
		MessageServiceGetMessagesProcedure,
		svc.GetMessages,
		connect.WithSchema(messageServiceMethods.ByName("GetMessages")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceGetMessageHandler := connect.NewUnaryHandler(
		MessageServiceGetMessageProcedure,
		svc.GetMessage,
		connect.WithSchema(messageServiceMethods.ByName("GetMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chat.message.v1.MessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MessageServiceGetMessagesProcedure:
			messageServiceGetMessagesHandler.ServeHTTP(w, r)
		case MessageServiceGetMessageProcedure:
			messageServiceGetMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMessageServiceHandler struct{}

func (UnimplementedMessageServiceHandler) GetMessages(context.Context, *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.message.v1.MessageService.GetMessages is not implemented"))
}

func (UnimplementedMessageServiceHandler) GetMessage(context.Context, *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.message.v1.MessageService.GetMessage is not implemented"))
}
