apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../base/external-secrets

labels:
  - pairs:
      environment: production
      app.kubernetes.io/managed-by: argocd
