// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: product/v1/product.proto

package productv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_product_v1_product_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_product_v1_product_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{0}
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *string                `protobuf:"bytes,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductsRequest) GetLimit() string {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return ""
}

func (x *ListProductsRequest) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *CursorPagination      `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetPagination() *CursorPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CursorPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    *string                `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	PrevCursor    *string                `protobuf:"bytes,2,opt,name=prev_cursor,json=prevCursor,proto3,oneof" json:"prev_cursor,omitempty"`
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,4,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPagination) Reset() {
	*x = CursorPagination{}
	mi := &file_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPagination) ProtoMessage() {}

func (x *CursorPagination) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPagination.ProtoReflect.Descriptor instead.
func (*CursorPagination) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *CursorPagination) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *CursorPagination) GetPrevCursor() string {
	if x != nil && x.PrevCursor != nil {
		return *x.PrevCursor
	}
	return ""
}

func (x *CursorPagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *CursorPagination) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

type BatchGetProductsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProductsByIDsRequest) Reset() {
	*x = BatchGetProductsByIDsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProductsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProductsByIDsRequest) ProtoMessage() {}

func (x *BatchGetProductsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProductsByIDsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetProductsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetProductsByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchGetProductsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProductsByIDsResponse) Reset() {
	*x = BatchGetProductsByIDsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProductsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProductsByIDsResponse) ProtoMessage() {}

func (x *BatchGetProductsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProductsByIDsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetProductsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetProductsByIDsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *BatchGetProductsByIDsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReserveProductsRequest struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	IdempotencyKey string                        `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Items          []*ProductQuantityWithVersion `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveProductsRequest) Reset() {
	*x = ReserveProductsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductsRequest) ProtoMessage() {}

func (x *ReserveProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductsRequest.ProtoReflect.Descriptor instead.
func (*ReserveProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveProductsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReserveProductsRequest) GetItems() []*ProductQuantityWithVersion {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProductQuantityWithVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // for optimistic locking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductQuantityWithVersion) Reset() {
	*x = ProductQuantityWithVersion{}
	mi := &file_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductQuantityWithVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductQuantityWithVersion) ProtoMessage() {}

func (x *ProductQuantityWithVersion) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductQuantityWithVersion.ProtoReflect.Descriptor instead.
func (*ProductQuantityWithVersion) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductQuantityWithVersion) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductQuantityWithVersion) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductQuantityWithVersion) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ProductQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductQuantity) Reset() {
	*x = ProductQuantity{}
	mi := &file_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductQuantity) ProtoMessage() {}

func (x *ProductQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductQuantity.ProtoReflect.Descriptor instead.
func (*ProductQuantity) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *ProductQuantity) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductQuantity) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveProductsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservedProducts []*Product             `protobuf:"bytes,2,rep,name=reserved_products,json=reservedProducts,proto3" json:"reserved_products,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReserveProductsResponse) Reset() {
	*x = ReserveProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductsResponse) ProtoMessage() {}

func (x *ReserveProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductsResponse.ProtoReflect.Descriptor instead.
func (*ReserveProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveProductsResponse) GetReservedProducts() []*Product {
	if x != nil {
		return x.ReservedProducts
	}
	return nil
}

func (x *ReserveProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Product struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price            float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity         int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Version          int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                                           // for optimistic locking
	ReservedQuantity int64                  `protobuf:"varint,6,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"` // quantity reserved for orders
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Product) GetReservedQuantity() int64 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReleaseProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductQuantity     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProductsRequest) Reset() {
	*x = ReleaseProductsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProductsRequest) ProtoMessage() {}

func (x *ReleaseProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProductsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseProductsRequest) GetItems() []*ProductQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProductsResponse) Reset() {
	*x = ReleaseProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProductsResponse) ProtoMessage() {}

func (x *ReleaseProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProductsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmProductsDeductionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductQuantity     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmProductsDeductionRequest) Reset() {
	*x = ConfirmProductsDeductionRequest{}
	mi := &file_product_v1_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmProductsDeductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmProductsDeductionRequest) ProtoMessage() {}

func (x *ConfirmProductsDeductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmProductsDeductionRequest.ProtoReflect.Descriptor instead.
func (*ConfirmProductsDeductionRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmProductsDeductionRequest) GetItems() []*ProductQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfirmProductsDeductionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedProducts []*Product             `protobuf:"bytes,2,rep,name=updated_products,json=updatedProducts,proto3" json:"updated_products,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmProductsDeductionResponse) Reset() {
	*x = ConfirmProductsDeductionResponse{}
	mi := &file_product_v1_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmProductsDeductionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmProductsDeductionResponse) ProtoMessage() {}

func (x *ConfirmProductsDeductionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmProductsDeductionResponse.ProtoReflect.Descriptor instead.
func (*ConfirmProductsDeductionResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmProductsDeductionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmProductsDeductionResponse) GetUpdatedProducts() []*Product {
	if x != nil {
		return x.UpdatedProducts
	}
	return nil
}

func (x *ConfirmProductsDeductionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductQuantity     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // reason for restoration (e.g., "order_cancelled", "payment_failed")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreProductsRequest) Reset() {
	*x = RestoreProductsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreProductsRequest) ProtoMessage() {}

func (x *RestoreProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreProductsRequest.ProtoReflect.Descriptor instead.
func (*RestoreProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{14}
}

func (x *RestoreProductsRequest) GetItems() []*ProductQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RestoreProductsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RestoreProductsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RestoredProducts []*Product             `protobuf:"bytes,2,rep,name=restored_products,json=restoredProducts,proto3" json:"restored_products,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreProductsResponse) Reset() {
	*x = RestoreProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreProductsResponse) ProtoMessage() {}

func (x *RestoreProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreProductsResponse.ProtoReflect.Descriptor instead.
func (*RestoreProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{15}
}

func (x *RestoreProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreProductsResponse) GetRestoredProducts() []*Product {
	if x != nil {
		return x.RestoredProducts
	}
	return nil
}

func (x *RestoreProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateProductsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Products      []*ProductForValidation `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductsRequest) Reset() {
	*x = ValidateProductsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductsRequest) ProtoMessage() {}

func (x *ValidateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductsRequest.ProtoReflect.Descriptor instead.
func (*ValidateProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateProductsRequest) GetProducts() []*ProductForValidation {
	if x != nil {
		return x.Products
	}
	return nil
}

type ValidateProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // true if all products are valid
	Products      []*Product             `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductsResponse) Reset() {
	*x = ValidateProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductsResponse) ProtoMessage() {}

func (x *ValidateProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductsResponse.ProtoReflect.Descriptor instead.
func (*ValidateProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ValidateProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProductForValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductForValidation) Reset() {
	*x = ProductForValidation{}
	mi := &file_product_v1_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductForValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductForValidation) ProtoMessage() {}

func (x *ProductForValidation) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductForValidation.ProtoReflect.Descriptor instead.
func (*ProductForValidation) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{18}
}

func (x *ProductForValidation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductForValidation) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductForValidation) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_product_v1_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{19}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=product.v1.HealthStatus" json:"status,omitempty"` // e.g., "SERVING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_product_v1_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

var File_product_v1_product_proto protoreflect.FileDescriptor

const file_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x18product/v1/product.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"y\n" +
	"\x13ListProductsRequest\x12\"\n" +
	"\x05limit\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18\x03H\x00R\x05limit\x88\x01\x01\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x01R\n" +
	"nextCursor\x88\x01\x01B\b\n" +
	"\x06_limitB\x0e\n" +
	"\f_next_cursor\"\x85\x01\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.product.v1.CursorPaginationR\n" +
	"pagination\"\xb4\x01\n" +
	"\x10CursorPagination\x12$\n" +
	"\vnext_cursor\x18\x01 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01\x12$\n" +
	"\vprev_cursor\x18\x02 \x01(\tH\x01R\n" +
	"prevCursor\x88\x01\x01\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x04 \x01(\bR\ahasPrevB\x0e\n" +
	"\f_next_cursorB\x0e\n" +
	"\f_prev_cursor\"C\n" +
	"\x1cBatchGetProductsByIDsRequest\x12#\n" +
	"\x03ids\x18\x01 \x03(\tB\x11\xbaH\x0e\x92\x01\v\b\x01\x10d\"\x05r\x03\xb0\x01\x01R\x03ids\"j\n" +
	"\x1dBatchGetProductsByIDsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x97\x01\n" +
	"\x16ReserveProductsRequest\x123\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x0eidempotencyKey\x12H\n" +
	"\x05items\x18\x02 \x03(\v2&.product.v1.ProductQuantityWithVersionB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x102R\x05items\"\x8d\x01\n" +
	"\x1aProductQuantityWithVersion\x12'\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tproductId\x12#\n" +
	"\bquantity\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\bquantity\x12!\n" +
	"\aversion\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\aversion\"_\n" +
	"\x0fProductQuantity\x12'\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tproductId\x12#\n" +
	"\bquantity\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\bquantity\"\x8f\x01\n" +
	"\x17ReserveProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\x11reserved_products\x18\x02 \x03(\v2\x13.product.v1.ProductR\x10reservedProducts\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xdd\x02\n" +
	"\aProduct\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12$\n" +
	"\x05price\x18\x03 \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x12#\n" +
	"\bquantity\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bquantity\x12!\n" +
	"\aversion\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\aversion\x124\n" +
	"\x11reserved_quantity\x18\x06 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x10reservedQuantity\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"W\n" +
	"\x16ReleaseProductsRequest\x12=\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.product.v1.ProductQuantityB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x102R\x05items\"M\n" +
	"\x17ReleaseProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x1fConfirmProductsDeductionRequest\x12=\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.product.v1.ProductQuantityB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x102R\x05items\"\x96\x01\n" +
	" ConfirmProductsDeductionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\x10updated_products\x18\x02 \x03(\v2\x13.product.v1.ProductR\x0fupdatedProducts\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"{\n" +
	"\x16RestoreProductsRequest\x12=\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.product.v1.ProductQuantityB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x102R\x05items\x12\"\n" +
	"\x06reason\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x06reason\"\x8f\x01\n" +
	"\x17RestoreProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\x11restored_products\x18\x02 \x03(\v2\x13.product.v1.ProductR\x10restoredProducts\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"W\n" +
	"\x17ValidateProductsRequest\x12<\n" +
	"\bproducts\x18\x01 \x03(\v2 .product.v1.ProductForValidationR\bproducts\"\x7f\n" +
	"\x18ValidateProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\bproducts\x18\x02 \x03(\v2\x13.product.v1.ProductR\bproducts\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"{\n" +
	"\x14ProductForValidation\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12$\n" +
	"\x05price\x18\x02 \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x12#\n" +
	"\bquantity\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bquantity\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.product.v1.HealthStatusR\x06status*g\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x022\xfc\x05\n" +
	"\x0eProductService\x12Q\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a .product.v1.ListProductsResponse\x12l\n" +
	"\x15BatchGetProductsByIDs\x12(.product.v1.BatchGetProductsByIDsRequest\x1a).product.v1.BatchGetProductsByIDsResponse\x12Z\n" +
	"\x0fReserveProducts\x12\".product.v1.ReserveProductsRequest\x1a#.product.v1.ReserveProductsResponse\x12Z\n" +
	"\x0fReleaseProducts\x12\".product.v1.ReleaseProductsRequest\x1a#.product.v1.ReleaseProductsResponse\x12u\n" +
	"\x18ConfirmProductsDeduction\x12+.product.v1.ConfirmProductsDeductionRequest\x1a,.product.v1.ConfirmProductsDeductionResponse\x12Z\n" +
	"\x0fRestoreProducts\x12\".product.v1.RestoreProductsRequest\x1a#.product.v1.RestoreProductsResponse\x12]\n" +
	"\x10ValidateProducts\x12#.product.v1.ValidateProductsRequest\x1a$.product.v1.ValidateProductsResponse\x12?\n" +
	"\x06Health\x12\x19.product.v1.HealthRequest\x1a\x1a.product.v1.HealthResponseB\xae\x01\n" +
	"\x0ecom.product.v1B\fProductProtoP\x01ZEgithub.com/raphaeldiscky/go-micro-commerce/proto/product/v1;productv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Product.V1\xca\x02\n" +
	"Product\\V1\xe2\x02\x16Product\\V1\\GPBMetadata\xea\x02\vProduct::V1b\x06proto3"

var (
	file_product_v1_product_proto_rawDescOnce sync.Once
	file_product_v1_product_proto_rawDescData []byte
)

func file_product_v1_product_proto_rawDescGZIP() []byte {
	file_product_v1_product_proto_rawDescOnce.Do(func() {
		file_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)))
	})
	return file_product_v1_product_proto_rawDescData
}

var file_product_v1_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_product_v1_product_proto_goTypes = []any{
	(HealthStatus)(0),                        // 0: product.v1.HealthStatus
	(*ListProductsRequest)(nil),              // 1: product.v1.ListProductsRequest
	(*ListProductsResponse)(nil),             // 2: product.v1.ListProductsResponse
	(*CursorPagination)(nil),                 // 3: product.v1.CursorPagination
	(*BatchGetProductsByIDsRequest)(nil),     // 4: product.v1.BatchGetProductsByIDsRequest
	(*BatchGetProductsByIDsResponse)(nil),    // 5: product.v1.BatchGetProductsByIDsResponse
	(*ReserveProductsRequest)(nil),           // 6: product.v1.ReserveProductsRequest
	(*ProductQuantityWithVersion)(nil),       // 7: product.v1.ProductQuantityWithVersion
	(*ProductQuantity)(nil),                  // 8: product.v1.ProductQuantity
	(*ReserveProductsResponse)(nil),          // 9: product.v1.ReserveProductsResponse
	(*Product)(nil),                          // 10: product.v1.Product
	(*ReleaseProductsRequest)(nil),           // 11: product.v1.ReleaseProductsRequest
	(*ReleaseProductsResponse)(nil),          // 12: product.v1.ReleaseProductsResponse
	(*ConfirmProductsDeductionRequest)(nil),  // 13: product.v1.ConfirmProductsDeductionRequest
	(*ConfirmProductsDeductionResponse)(nil), // 14: product.v1.ConfirmProductsDeductionResponse
	(*RestoreProductsRequest)(nil),           // 15: product.v1.RestoreProductsRequest
	(*RestoreProductsResponse)(nil),          // 16: product.v1.RestoreProductsResponse
	(*ValidateProductsRequest)(nil),          // 17: product.v1.ValidateProductsRequest
	(*ValidateProductsResponse)(nil),         // 18: product.v1.ValidateProductsResponse
	(*ProductForValidation)(nil),             // 19: product.v1.ProductForValidation
	(*HealthRequest)(nil),                    // 20: product.v1.HealthRequest
	(*HealthResponse)(nil),                   // 21: product.v1.HealthResponse
	(*timestamppb.Timestamp)(nil),            // 22: google.protobuf.Timestamp
}
var file_product_v1_product_proto_depIdxs = []int32{
	10, // 0: product.v1.ListProductsResponse.products:type_name -> product.v1.Product
	3,  // 1: product.v1.ListProductsResponse.pagination:type_name -> product.v1.CursorPagination
	10, // 2: product.v1.BatchGetProductsByIDsResponse.products:type_name -> product.v1.Product
	7,  // 3: product.v1.ReserveProductsRequest.items:type_name -> product.v1.ProductQuantityWithVersion
	10, // 4: product.v1.ReserveProductsResponse.reserved_products:type_name -> product.v1.Product
	22, // 5: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	22, // 6: product.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 7: product.v1.ReleaseProductsRequest.items:type_name -> product.v1.ProductQuantity
	8,  // 8: product.v1.ConfirmProductsDeductionRequest.items:type_name -> product.v1.ProductQuantity
	10, // 9: product.v1.ConfirmProductsDeductionResponse.updated_products:type_name -> product.v1.Product
	8,  // 10: product.v1.RestoreProductsRequest.items:type_name -> product.v1.ProductQuantity
	10, // 11: product.v1.RestoreProductsResponse.restored_products:type_name -> product.v1.Product
	19, // 12: product.v1.ValidateProductsRequest.products:type_name -> product.v1.ProductForValidation
	10, // 13: product.v1.ValidateProductsResponse.products:type_name -> product.v1.Product
	0,  // 14: product.v1.HealthResponse.status:type_name -> product.v1.HealthStatus
	1,  // 15: product.v1.ProductService.ListProducts:input_type -> product.v1.ListProductsRequest
	4,  // 16: product.v1.ProductService.BatchGetProductsByIDs:input_type -> product.v1.BatchGetProductsByIDsRequest
	6,  // 17: product.v1.ProductService.ReserveProducts:input_type -> product.v1.ReserveProductsRequest
	11, // 18: product.v1.ProductService.ReleaseProducts:input_type -> product.v1.ReleaseProductsRequest
	13, // 19: product.v1.ProductService.ConfirmProductsDeduction:input_type -> product.v1.ConfirmProductsDeductionRequest
	15, // 20: product.v1.ProductService.RestoreProducts:input_type -> product.v1.RestoreProductsRequest
	17, // 21: product.v1.ProductService.ValidateProducts:input_type -> product.v1.ValidateProductsRequest
	20, // 22: product.v1.ProductService.Health:input_type -> product.v1.HealthRequest
	2,  // 23: product.v1.ProductService.ListProducts:output_type -> product.v1.ListProductsResponse
	5,  // 24: product.v1.ProductService.BatchGetProductsByIDs:output_type -> product.v1.BatchGetProductsByIDsResponse
	9,  // 25: product.v1.ProductService.ReserveProducts:output_type -> product.v1.ReserveProductsResponse
	12, // 26: product.v1.ProductService.ReleaseProducts:output_type -> product.v1.ReleaseProductsResponse
	14, // 27: product.v1.ProductService.ConfirmProductsDeduction:output_type -> product.v1.ConfirmProductsDeductionResponse
	16, // 28: product.v1.ProductService.RestoreProducts:output_type -> product.v1.RestoreProductsResponse
	18, // 29: product.v1.ProductService.ValidateProducts:output_type -> product.v1.ValidateProductsResponse
	21, // 30: product.v1.ProductService.Health:output_type -> product.v1.HealthResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_product_v1_product_proto_init() }
func file_product_v1_product_proto_init() {
	if File_product_v1_product_proto != nil {
		return
	}
	file_product_v1_product_proto_msgTypes[0].OneofWrappers = []any{}
	file_product_v1_product_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_product_proto_goTypes,
		DependencyIndexes: file_product_v1_product_proto_depIdxs,
		EnumInfos:         file_product_v1_product_proto_enumTypes,
		MessageInfos:      file_product_v1_product_proto_msgTypes,
	}.Build()
	File_product_v1_product_proto = out.File
	file_product_v1_product_proto_goTypes = nil
	file_product_v1_product_proto_depIdxs = nil
}
