// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chat/conversation/v1/conversation.proto

package conversationv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/raphaeldiscky/go-micro-commerce/proto/chat/conversation/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConversationServiceName is the fully-qualified name of the ConversationService service.
	ConversationServiceName = "chat.conversation.v1.ConversationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConversationServiceGetUserConversationsProcedure is the fully-qualified name of the
	// ConversationService's GetUserConversations RPC.
	ConversationServiceGetUserConversationsProcedure = "/chat.conversation.v1.ConversationService/GetUserConversations"
	// ConversationServiceCreateConversationProcedure is the fully-qualified name of the
	// ConversationService's CreateConversation RPC.
	ConversationServiceCreateConversationProcedure = "/chat.conversation.v1.ConversationService/CreateConversation"
	// ConversationServiceGetConversationProcedure is the fully-qualified name of the
	// ConversationService's GetConversation RPC.
	ConversationServiceGetConversationProcedure = "/chat.conversation.v1.ConversationService/GetConversation"
	// ConversationServiceUpdateConversationStatusProcedure is the fully-qualified name of the
	// ConversationService's UpdateConversationStatus RPC.
	ConversationServiceUpdateConversationStatusProcedure = "/chat.conversation.v1.ConversationService/UpdateConversationStatus"
	// ConversationServiceJoinConversationProcedure is the fully-qualified name of the
	// ConversationService's JoinConversation RPC.
	ConversationServiceJoinConversationProcedure = "/chat.conversation.v1.ConversationService/JoinConversation"
)

// ConversationServiceClient is a client for the chat.conversation.v1.ConversationService service.
type ConversationServiceClient interface {
	// GetUserConversations retrieves all conversations for a user
	GetUserConversations(context.Context, *connect.Request[v1.GetUserConversationsRequest]) (*connect.Response[v1.GetUserConversationsResponse], error)
	// CreateConversation creates a new conversation
	CreateConversation(context.Context, *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.CreateConversationResponse], error)
	// GetConversation retrieves a conversation by ID
	GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error)
	// UpdateConversationStatus updates conversation status
	UpdateConversationStatus(context.Context, *connect.Request[v1.UpdateConversationStatusRequest]) (*connect.Response[v1.UpdateConversationStatusResponse], error)
	// JoinConversation adds a participant to a conversation (data operation)
	JoinConversation(context.Context, *connect.Request[v1.JoinConversationRequest]) (*connect.Response[v1.JoinConversationResponse], error)
}

// NewConversationServiceClient constructs a client for the chat.conversation.v1.ConversationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConversationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConversationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	conversationServiceMethods := v1.File_chat_conversation_v1_conversation_proto.Services().ByName("ConversationService").Methods()
	return &conversationServiceClient{
		getUserConversations: connect.NewClient[v1.GetUserConversationsRequest, v1.GetUserConversationsResponse](
			httpClient,
			baseURL+ConversationServiceGetUserConversationsProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("GetUserConversations")),
			connect.WithClientOptions(opts...),
		),
		createConversation: connect.NewClient[v1.CreateConversationRequest, v1.CreateConversationResponse](
			httpClient,
			baseURL+ConversationServiceCreateConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("CreateConversation")),
			connect.WithClientOptions(opts...),
		),
		getConversation: connect.NewClient[v1.GetConversationRequest, v1.GetConversationResponse](
			httpClient,
			baseURL+ConversationServiceGetConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("GetConversation")),
			connect.WithClientOptions(opts...),
		),
		updateConversationStatus: connect.NewClient[v1.UpdateConversationStatusRequest, v1.UpdateConversationStatusResponse](
			httpClient,
			baseURL+ConversationServiceUpdateConversationStatusProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("UpdateConversationStatus")),
			connect.WithClientOptions(opts...),
		),
		joinConversation: connect.NewClient[v1.JoinConversationRequest, v1.JoinConversationResponse](
			httpClient,
			baseURL+ConversationServiceJoinConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("JoinConversation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// conversationServiceClient implements ConversationServiceClient.
type conversationServiceClient struct {
	getUserConversations     *connect.Client[v1.GetUserConversationsRequest, v1.GetUserConversationsResponse]
	createConversation       *connect.Client[v1.CreateConversationRequest, v1.CreateConversationResponse]
	getConversation          *connect.Client[v1.GetConversationRequest, v1.GetConversationResponse]
	updateConversationStatus *connect.Client[v1.UpdateConversationStatusRequest, v1.UpdateConversationStatusResponse]
	joinConversation         *connect.Client[v1.JoinConversationRequest, v1.JoinConversationResponse]
}

// GetUserConversations calls chat.conversation.v1.ConversationService.GetUserConversations.
func (c *conversationServiceClient) GetUserConversations(ctx context.Context, req *connect.Request[v1.GetUserConversationsRequest]) (*connect.Response[v1.GetUserConversationsResponse], error) {
	return c.getUserConversations.CallUnary(ctx, req)
}

// CreateConversation calls chat.conversation.v1.ConversationService.CreateConversation.
func (c *conversationServiceClient) CreateConversation(ctx context.Context, req *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.CreateConversationResponse], error) {
	return c.createConversation.CallUnary(ctx, req)
}

// GetConversation calls chat.conversation.v1.ConversationService.GetConversation.
func (c *conversationServiceClient) GetConversation(ctx context.Context, req *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error) {
	return c.getConversation.CallUnary(ctx, req)
}

// UpdateConversationStatus calls chat.conversation.v1.ConversationService.UpdateConversationStatus.
func (c *conversationServiceClient) UpdateConversationStatus(ctx context.Context, req *connect.Request[v1.UpdateConversationStatusRequest]) (*connect.Response[v1.UpdateConversationStatusResponse], error) {
	return c.updateConversationStatus.CallUnary(ctx, req)
}

// JoinConversation calls chat.conversation.v1.ConversationService.JoinConversation.
func (c *conversationServiceClient) JoinConversation(ctx context.Context, req *connect.Request[v1.JoinConversationRequest]) (*connect.Response[v1.JoinConversationResponse], error) {
	return c.joinConversation.CallUnary(ctx, req)
}

// ConversationServiceHandler is an implementation of the chat.conversation.v1.ConversationService
// service.
type ConversationServiceHandler interface {
	// GetUserConversations retrieves all conversations for a user
	GetUserConversations(context.Context, *connect.Request[v1.GetUserConversationsRequest]) (*connect.Response[v1.GetUserConversationsResponse], error)
	// CreateConversation creates a new conversation
	CreateConversation(context.Context, *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.CreateConversationResponse], error)
	// GetConversation retrieves a conversation by ID
	GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error)
	// UpdateConversationStatus updates conversation status
	UpdateConversationStatus(context.Context, *connect.Request[v1.UpdateConversationStatusRequest]) (*connect.Response[v1.UpdateConversationStatusResponse], error)
	// JoinConversation adds a participant to a conversation (data operation)
	JoinConversation(context.Context, *connect.Request[v1.JoinConversationRequest]) (*connect.Response[v1.JoinConversationResponse], error)
}

// NewConversationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConversationServiceHandler(svc ConversationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	conversationServiceMethods := v1.File_chat_conversation_v1_conversation_proto.Services().ByName("ConversationService").Methods()
	conversationServiceGetUserConversationsHandler := connect.NewUnaryHandler(
		ConversationServiceGetUserConversationsProcedure,
		svc.GetUserConversations,
		connect.WithSchema(conversationServiceMethods.ByName("GetUserConversations")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceCreateConversationHandler := connect.NewUnaryHandler(
		ConversationServiceCreateConversationProcedure,
		svc.CreateConversation,
		connect.WithSchema(conversationServiceMethods.ByName("CreateConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceGetConversationHandler := connect.NewUnaryHandler(
		ConversationServiceGetConversationProcedure,
		svc.GetConversation,
		connect.WithSchema(conversationServiceMethods.ByName("GetConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceUpdateConversationStatusHandler := connect.NewUnaryHandler(
		ConversationServiceUpdateConversationStatusProcedure,
		svc.UpdateConversationStatus,
		connect.WithSchema(conversationServiceMethods.ByName("UpdateConversationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceJoinConversationHandler := connect.NewUnaryHandler(
		ConversationServiceJoinConversationProcedure,
		svc.JoinConversation,
		connect.WithSchema(conversationServiceMethods.ByName("JoinConversation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chat.conversation.v1.ConversationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConversationServiceGetUserConversationsProcedure:
			conversationServiceGetUserConversationsHandler.ServeHTTP(w, r)
		case ConversationServiceCreateConversationProcedure:
			conversationServiceCreateConversationHandler.ServeHTTP(w, r)
		case ConversationServiceGetConversationProcedure:
			conversationServiceGetConversationHandler.ServeHTTP(w, r)
		case ConversationServiceUpdateConversationStatusProcedure:
			conversationServiceUpdateConversationStatusHandler.ServeHTTP(w, r)
		case ConversationServiceJoinConversationProcedure:
			conversationServiceJoinConversationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConversationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConversationServiceHandler struct{}

func (UnimplementedConversationServiceHandler) GetUserConversations(context.Context, *connect.Request[v1.GetUserConversationsRequest]) (*connect.Response[v1.GetUserConversationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.conversation.v1.ConversationService.GetUserConversations is not implemented"))
}

func (UnimplementedConversationServiceHandler) CreateConversation(context.Context, *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.CreateConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.conversation.v1.ConversationService.CreateConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.conversation.v1.ConversationService.GetConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) UpdateConversationStatus(context.Context, *connect.Request[v1.UpdateConversationStatusRequest]) (*connect.Response[v1.UpdateConversationStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.conversation.v1.ConversationService.UpdateConversationStatus is not implemented"))
}

func (UnimplementedConversationServiceHandler) JoinConversation(context.Context, *connect.Request[v1.JoinConversationRequest]) (*connect.Response[v1.JoinConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.conversation.v1.ConversationService.JoinConversation is not implemented"))
}
