apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

metadata:
  name: order-service

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: order-service
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: go-micro-commerce

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - migration-job.yaml

images:
  - name: order-service
    newName: order-service
    newTag: v0.0.0
  - name: order-service-migrations
    newName: order-service-migrations
    newTag: v0.0.0
