apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: order-service
    matchExpressions:
      - key: component
        operator: NotIn
        values:
          - migration
