// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/raphaeldiscky/go-micro-commerce/notification-service/internal/constant"
)

type NotificationEvent interface {
	IsNotificationEvent()
}

type Mutation struct {
}

type NewNotification struct {
	ID        string                        `json:"id"`
	UserID    string                        `json:"userId"`
	Type      constant.PushNotificationType `json:"type"`
	Title     string                        `json:"title"`
	Message   string                        `json:"message"`
	Metadata  *string                       `json:"metadata,omitempty"`
	IsRead    bool                          `json:"isRead"`
	CreatedAt time.Time                     `json:"createdAt"`
}

func (NewNotification) IsNotificationEvent() {}

type Notification struct {
	ID        string                        `json:"id"`
	UserID    string                        `json:"userId"`
	Type      constant.PushNotificationType `json:"type"`
	Title     string                        `json:"title"`
	Message   string                        `json:"message"`
	Metadata  *string                       `json:"metadata,omitempty"`
	IsRead    bool                          `json:"isRead"`
	ReadAt    *time.Time                    `json:"readAt,omitempty"`
	CreatedAt time.Time                     `json:"createdAt"`
	UpdatedAt time.Time                     `json:"updatedAt"`
}

type NotificationConnection struct {
	Edges    []*NotificationEdge `json:"edges"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type NotificationDeleted struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
}

func (NotificationDeleted) IsNotificationEvent() {}

type NotificationEdge struct {
	Node   *Notification `json:"node"`
	Cursor string        `json:"cursor"`
}

type NotificationRead struct {
	ID     string    `json:"id"`
	UserID string    `json:"userId"`
	ReadAt time.Time `json:"readAt"`
}

func (NotificationRead) IsNotificationEvent() {}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type TabCounts struct {
	All    int `json:"all"`
	Unread int `json:"unread"`
	Read   int `json:"read"`
}

type UnreadCount struct {
	Count int `json:"count"`
}

type User struct {
	ID            string          `json:"id"`
	Notifications []*Notification `json:"notifications"`
	UnreadCount   int             `json:"unreadCount"`
}

func (User) IsEntity() {}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
