apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway

components:
  - ../_common

resources:
  - ../../../base/gateway

labels:
  - pairs:
      environment: production
      app.kubernetes.io/managed-by: argocd

patches:
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: api-gateway-config
  - path: patch-httproute.yaml
    target:
      kind: HTTPRoute
      name: api-gateway-route
  - path: patch-middlewares.yaml
    target:
      kind: Middleware
      name: api-cors

images:
  - name: ghcr.io/raphaeldiscky/go-micro-commerce/api-gateway
    newTag: 0.1.13
