apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  podSelector:
    matchLabels:
      app: chat-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8088
        - protocol: TCP
          port: 8089
