apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chat-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: chat-service
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: chat-service
    matchExpressions:
      - key: component
        operator: NotIn
        values:
          - migration
