apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 50052
    targetPort: grpc
    protocol: TCP
  sessionAffinity: None
