apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_USER: "{{ .postgres_username }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        JWT_SECRET: "{{ .jwt_secret }}"
  data:
    - secretKey: postgres_username
      remoteRef:
        key: prod-postgres-auth-username
    - secretKey: postgres_password
      remoteRef:
        key: prod-postgres-auth-password
    - secretKey: jwt_secret
      remoteRef:
        key: prod-jwt-auth-secret
