apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cart-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: cart-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_USER: "{{ .postgres_username }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
  data:
    - secretKey: postgres_username
      remoteRef:
        key: prod-postgres-cart-username
    - secretKey: postgres_password
      remoteRef:
        key: prod-postgres-cart-password
