// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fulfillment/v1/fulfillment.proto

package fulfillmentv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/raphaeldiscky/go-micro-commerce/proto/fulfillment/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FulfillmentServiceName is the fully-qualified name of the FulfillmentService service.
	FulfillmentServiceName = "fulfillment.v1.FulfillmentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FulfillmentServiceGetShippingCostProcedure is the fully-qualified name of the
	// FulfillmentService's GetShippingCost RPC.
	FulfillmentServiceGetShippingCostProcedure = "/fulfillment.v1.FulfillmentService/GetShippingCost"
	// FulfillmentServiceHealthProcedure is the fully-qualified name of the FulfillmentService's Health
	// RPC.
	FulfillmentServiceHealthProcedure = "/fulfillment.v1.FulfillmentService/Health"
)

// FulfillmentServiceClient is a client for the fulfillment.v1.FulfillmentService service.
type FulfillmentServiceClient interface {
	GetShippingCost(context.Context, *connect.Request[v1.GetShippingCostRequest]) (*connect.Response[v1.GetShippingCostResponse], error)
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewFulfillmentServiceClient constructs a client for the fulfillment.v1.FulfillmentService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFulfillmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FulfillmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fulfillmentServiceMethods := v1.File_fulfillment_v1_fulfillment_proto.Services().ByName("FulfillmentService").Methods()
	return &fulfillmentServiceClient{
		getShippingCost: connect.NewClient[v1.GetShippingCostRequest, v1.GetShippingCostResponse](
			httpClient,
			baseURL+FulfillmentServiceGetShippingCostProcedure,
			connect.WithSchema(fulfillmentServiceMethods.ByName("GetShippingCost")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+FulfillmentServiceHealthProcedure,
			connect.WithSchema(fulfillmentServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fulfillmentServiceClient implements FulfillmentServiceClient.
type fulfillmentServiceClient struct {
	getShippingCost *connect.Client[v1.GetShippingCostRequest, v1.GetShippingCostResponse]
	health          *connect.Client[v1.HealthRequest, v1.HealthResponse]
}

// GetShippingCost calls fulfillment.v1.FulfillmentService.GetShippingCost.
func (c *fulfillmentServiceClient) GetShippingCost(ctx context.Context, req *connect.Request[v1.GetShippingCostRequest]) (*connect.Response[v1.GetShippingCostResponse], error) {
	return c.getShippingCost.CallUnary(ctx, req)
}

// Health calls fulfillment.v1.FulfillmentService.Health.
func (c *fulfillmentServiceClient) Health(ctx context.Context, req *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// FulfillmentServiceHandler is an implementation of the fulfillment.v1.FulfillmentService service.
type FulfillmentServiceHandler interface {
	GetShippingCost(context.Context, *connect.Request[v1.GetShippingCostRequest]) (*connect.Response[v1.GetShippingCostResponse], error)
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewFulfillmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFulfillmentServiceHandler(svc FulfillmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fulfillmentServiceMethods := v1.File_fulfillment_v1_fulfillment_proto.Services().ByName("FulfillmentService").Methods()
	fulfillmentServiceGetShippingCostHandler := connect.NewUnaryHandler(
		FulfillmentServiceGetShippingCostProcedure,
		svc.GetShippingCost,
		connect.WithSchema(fulfillmentServiceMethods.ByName("GetShippingCost")),
		connect.WithHandlerOptions(opts...),
	)
	fulfillmentServiceHealthHandler := connect.NewUnaryHandler(
		FulfillmentServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(fulfillmentServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fulfillment.v1.FulfillmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FulfillmentServiceGetShippingCostProcedure:
			fulfillmentServiceGetShippingCostHandler.ServeHTTP(w, r)
		case FulfillmentServiceHealthProcedure:
			fulfillmentServiceHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFulfillmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFulfillmentServiceHandler struct{}

func (UnimplementedFulfillmentServiceHandler) GetShippingCost(context.Context, *connect.Request[v1.GetShippingCostRequest]) (*connect.Response[v1.GetShippingCostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fulfillment.v1.FulfillmentService.GetShippingCost is not implemented"))
}

func (UnimplementedFulfillmentServiceHandler) Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fulfillment.v1.FulfillmentService.Health is not implemented"))
}
