// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file user/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
  GenService,
} from '@bufbuild/protobuf/codegenv2'
import {
  enumDesc,
  fileDesc,
  messageDesc,
  serviceDesc,
} from '@bufbuild/protobuf/codegenv2'
import type { Timestamp } from '@bufbuild/protobuf/wkt'
import { file_google_protobuf_timestamp } from '@bufbuild/protobuf/wkt'
import { file_buf_validate_validate } from '../buf/validate/validate_pb'
import type { Message } from '@bufbuild/protobuf'

/**
 * Describes the file user/user.proto.
 */
export const file_user_user: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Cg91c2VyL3VzZXIucHJvdG8SB3VzZXIudjEiKgoSR2V0VXNlckJ5SURSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA7ABASIyChNHZXRVc2VyQnlJRFJlc3BvbnNlEhsKBHVzZXIYASABKAsyDS51c2VyLnYxLlVzZXIirgEKBFVzZXISFAoCaWQYASABKAlCCLpIBXIDsAEBEhgKBG5hbWUYAiABKAlCCrpIB3IFEAEY/wESFgoFZW1haWwYAyABKAlCB7pIBHICYAESLgoKY3JlYXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiDwoNSGVhbHRoUmVxdWVzdCI3Cg5IZWFsdGhSZXNwb25zZRIlCgZzdGF0dXMYASABKA4yFS51c2VyLnYxLkhlYWx0aFN0YXR1cypnCgxIZWFsdGhTdGF0dXMSHQoZSEVBTFRIX1NUQVRVU19VTlNQRUNJRklFRBAAEhkKFUhFQUxUSF9TVEFUVVNfU0VSVklORxABEh0KGUhFQUxUSF9TVEFUVVNfTk9UX1NFUlZJTkcQAjKSAQoLVXNlclNlcnZpY2USSAoLZ2V0VXNlckJ5SUQSGy51c2VyLnYxLkdldFVzZXJCeUlEUmVxdWVzdBocLnVzZXIudjEuR2V0VXNlckJ5SURSZXNwb25zZRI5CgZIZWFsdGgSFi51c2VyLnYxLkhlYWx0aFJlcXVlc3QaFy51c2VyLnYxLkhlYWx0aFJlc3BvbnNlQpYBCgtjb20udXNlci52MUIJVXNlclByb3RvUAFaP2dpdGh1Yi5jb20vcmFwaGFlbGRpc2NreS9nby1taWNyby1jb21tZXJjZS9wcm90by91c2VyL3YxO3VzZXJ2MaICA1VYWKoCB1VzZXIuVjHKAgdVc2VyXFYx4gITVXNlclxWMVxHUEJNZXRhZGF0YeoCCFVzZXI6OlYxYgZwcm90bzM',
    [file_google_protobuf_timestamp, file_buf_validate_validate],
  )

/**
 * @generated from message user.v1.GetUserByIDRequest
 */
export type GetUserByIDRequest = Message<'user.v1.GetUserByIDRequest'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string
}

/**
 * Describes the message user.v1.GetUserByIDRequest.
 * Use `create(GetUserByIDRequestSchema)` to create a new message.
 */
export const GetUserByIDRequestSchema: GenMessage<GetUserByIDRequest> =
  /*@__PURE__*/
  messageDesc(file_user_user, 0)

/**
 * @generated from message user.v1.GetUserByIDResponse
 */
export type GetUserByIDResponse = Message<'user.v1.GetUserByIDResponse'> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User
}

/**
 * Describes the message user.v1.GetUserByIDResponse.
 * Use `create(GetUserByIDResponseSchema)` to create a new message.
 */
export const GetUserByIDResponseSchema: GenMessage<GetUserByIDResponse> =
  /*@__PURE__*/
  messageDesc(file_user_user, 1)

/**
 * @generated from message user.v1.User
 */
export type User = Message<'user.v1.User'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string

  /**
   * @generated from field: string name = 2;
   */
  name: string

  /**
   * @generated from field: string email = 3;
   */
  email: string

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp
}

/**
 * Describes the message user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> =
  /*@__PURE__*/
  messageDesc(file_user_user, 2)

/**
 * @generated from message user.v1.HealthRequest
 */
export type HealthRequest = Message<'user.v1.HealthRequest'> & {}

/**
 * Describes the message user.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export const HealthRequestSchema: GenMessage<HealthRequest> =
  /*@__PURE__*/
  messageDesc(file_user_user, 3)

/**
 * @generated from message user.v1.HealthResponse
 */
export type HealthResponse = Message<'user.v1.HealthResponse'> & {
  /**
   * e.g., "SERVING"
   *
   * @generated from field: user.v1.HealthStatus status = 1;
   */
  status: HealthStatus
}

/**
 * Describes the message user.v1.HealthResponse.
 * Use `create(HealthResponseSchema)` to create a new message.
 */
export const HealthResponseSchema: GenMessage<HealthResponse> =
  /*@__PURE__*/
  messageDesc(file_user_user, 4)

/**
 * @generated from enum user.v1.HealthStatus
 */
export enum HealthStatus {
  /**
   * @generated from enum value: HEALTH_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: HEALTH_STATUS_SERVING = 1;
   */
  SERVING = 1,

  /**
   * @generated from enum value: HEALTH_STATUS_NOT_SERVING = 2;
   */
  NOT_SERVING = 2,
}

/**
 * Describes the enum user.v1.HealthStatus.
 */
export const HealthStatusSchema: GenEnum<HealthStatus> =
  /*@__PURE__*/
  enumDesc(file_user_user, 0)

/**
 * User service definition
 *
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.v1.UserService.getUserByID
   */
  getUserByID: {
    methodKind: 'unary'
    input: typeof GetUserByIDRequestSchema
    output: typeof GetUserByIDResponseSchema
  }
  /**
   * @generated from rpc user.v1.UserService.Health
   */
  health: {
    methodKind: 'unary'
    input: typeof HealthRequestSchema
    output: typeof HealthResponseSchema
  }
}> = /*@__PURE__*/ serviceDesc(file_user_user, 0)
