apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

metadata:
  name: fulfillment-service

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: fulfillment-service
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: go-micro-commerce

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

images:
  - name: fulfillment-service
    newName: fulfillment-service
    newTag: latest
  - name: fulfillment-service-migrations
    newName: fulfillment-service-migrations
    newTag: latest
