apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fulfillment-service
  labels:
    app: fulfillment-service
spec:
  podSelector:
    matchLabels:
      app: fulfillment-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8085
