apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fulfillment-service
  labels:
    app: fulfillment-service
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: fulfillment-service
