apiVersion: v1
kind: ServiceAccount
metadata:
  name: fulfillment-service
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: fulfillment-service
automountServiceAccountToken: true
