// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/seller.proto

package marketplacev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Seller messages
type Seller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seller) Reset() {
	*x = Seller{}
	mi := &file_proto_seller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seller) ProtoMessage() {}

func (x *Seller) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seller.ProtoReflect.Descriptor instead.
func (*Seller) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{0}
}

func (x *Seller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seller) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Seller) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateSellerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSellerRequest) Reset() {
	*x = CreateSellerRequest{}
	mi := &file_proto_seller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellerRequest) ProtoMessage() {}

func (x *CreateSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellerRequest.ProtoReflect.Descriptor instead.
func (*CreateSellerRequest) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSellerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSellerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        *Seller                `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSellerResponse) Reset() {
	*x = CreateSellerResponse{}
	mi := &file_proto_seller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellerResponse) ProtoMessage() {}

func (x *CreateSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellerResponse.ProtoReflect.Descriptor instead.
func (*CreateSellerResponse) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSellerResponse) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type GetSellerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerRequest) Reset() {
	*x = GetSellerRequest{}
	mi := &file_proto_seller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerRequest) ProtoMessage() {}

func (x *GetSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerRequest.ProtoReflect.Descriptor instead.
func (*GetSellerRequest) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{3}
}

func (x *GetSellerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSellerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        *Seller                `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerResponse) Reset() {
	*x = GetSellerResponse{}
	mi := &file_proto_seller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerResponse) ProtoMessage() {}

func (x *GetSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerResponse.ProtoReflect.Descriptor instead.
func (*GetSellerResponse) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{4}
}

func (x *GetSellerResponse) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type ListSellersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSellersRequest) Reset() {
	*x = ListSellersRequest{}
	mi := &file_proto_seller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSellersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSellersRequest) ProtoMessage() {}

func (x *ListSellersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSellersRequest.ProtoReflect.Descriptor instead.
func (*ListSellersRequest) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{5}
}

func (x *ListSellersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSellersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSellersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sellers       []*Seller              `protobuf:"bytes,1,rep,name=sellers,proto3" json:"sellers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSellersResponse) Reset() {
	*x = ListSellersResponse{}
	mi := &file_proto_seller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSellersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSellersResponse) ProtoMessage() {}

func (x *ListSellersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSellersResponse.ProtoReflect.Descriptor instead.
func (*ListSellersResponse) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{6}
}

func (x *ListSellersResponse) GetSellers() []*Seller {
	if x != nil {
		return x.Sellers
	}
	return nil
}

func (x *ListSellersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSellersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSellersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateSellerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSellerRequest) Reset() {
	*x = UpdateSellerRequest{}
	mi := &file_proto_seller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerRequest) ProtoMessage() {}

func (x *UpdateSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerRequest.ProtoReflect.Descriptor instead.
func (*UpdateSellerRequest) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSellerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSellerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateSellerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        *Seller                `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSellerResponse) Reset() {
	*x = UpdateSellerResponse{}
	mi := &file_proto_seller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerResponse) ProtoMessage() {}

func (x *UpdateSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerResponse.ProtoReflect.Descriptor instead.
func (*UpdateSellerResponse) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSellerResponse) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type DeleteSellerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellerRequest) Reset() {
	*x = DeleteSellerRequest{}
	mi := &file_proto_seller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellerRequest) ProtoMessage() {}

func (x *DeleteSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellerRequest.ProtoReflect.Descriptor instead.
func (*DeleteSellerRequest) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSellerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSellerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellerResponse) Reset() {
	*x = DeleteSellerResponse{}
	mi := &file_proto_seller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellerResponse) ProtoMessage() {}

func (x *DeleteSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellerResponse.ProtoReflect.Descriptor instead.
func (*DeleteSellerResponse) Descriptor() ([]byte, []int) {
	return file_proto_seller_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSellerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_seller_proto protoreflect.FileDescriptor

const file_proto_seller_proto_rawDesc = "" +
	"\n" +
	"\x12proto/seller.proto\x12\x0emarketplace.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x06Seller\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\")\n" +
	"\x13CreateSellerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x14CreateSellerResponse\x12.\n" +
	"\x06seller\x18\x01 \x01(\v2\x16.marketplace.v1.SellerR\x06seller\"\"\n" +
	"\x10GetSellerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x11GetSellerResponse\x12.\n" +
	"\x06seller\x18\x01 \x01(\v2\x16.marketplace.v1.SellerR\x06seller\"E\n" +
	"\x12ListSellersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8e\x01\n" +
	"\x13ListSellersResponse\x120\n" +
	"\asellers\x18\x01 \x03(\v2\x16.marketplace.v1.SellerR\asellers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"9\n" +
	"\x13UpdateSellerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\x14UpdateSellerResponse\x12.\n" +
	"\x06seller\x18\x01 \x01(\v2\x16.marketplace.v1.SellerR\x06seller\"%\n" +
	"\x13DeleteSellerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteSellerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xca\x03\n" +
	"\rSellerService\x12Y\n" +
	"\fCreateSeller\x12#.marketplace.v1.CreateSellerRequest\x1a$.marketplace.v1.CreateSellerResponse\x12P\n" +
	"\tGetSeller\x12 .marketplace.v1.GetSellerRequest\x1a!.marketplace.v1.GetSellerResponse\x12V\n" +
	"\vListSellers\x12\".marketplace.v1.ListSellersRequest\x1a#.marketplace.v1.ListSellersResponse\x12Y\n" +
	"\fUpdateSeller\x12#.marketplace.v1.UpdateSellerRequest\x1a$.marketplace.v1.UpdateSellerResponse\x12Y\n" +
	"\fDeleteSeller\x12#.marketplace.v1.DeleteSellerRequest\x1a$.marketplace.v1.DeleteSellerResponseB@Z>github.com/raphaeldiscky/go-ddd-template/proto/marketplace/v1;marketplacev1b\x06proto3"

var (
	file_proto_seller_proto_rawDescOnce sync.Once
	file_proto_seller_proto_rawDescData []byte
)

func file_proto_seller_proto_rawDescGZIP() []byte {
	file_proto_seller_proto_rawDescOnce.Do(func() {
		file_proto_seller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_seller_proto_rawDesc), len(file_proto_seller_proto_rawDesc)))
	})
	return file_proto_seller_proto_rawDescData
}

var file_proto_seller_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_seller_proto_goTypes = []any{
	(*Seller)(nil),                // 0: marketplace.v1.Seller
	(*CreateSellerRequest)(nil),   // 1: marketplace.v1.CreateSellerRequest
	(*CreateSellerResponse)(nil),  // 2: marketplace.v1.CreateSellerResponse
	(*GetSellerRequest)(nil),      // 3: marketplace.v1.GetSellerRequest
	(*GetSellerResponse)(nil),     // 4: marketplace.v1.GetSellerResponse
	(*ListSellersRequest)(nil),    // 5: marketplace.v1.ListSellersRequest
	(*ListSellersResponse)(nil),   // 6: marketplace.v1.ListSellersResponse
	(*UpdateSellerRequest)(nil),   // 7: marketplace.v1.UpdateSellerRequest
	(*UpdateSellerResponse)(nil),  // 8: marketplace.v1.UpdateSellerResponse
	(*DeleteSellerRequest)(nil),   // 9: marketplace.v1.DeleteSellerRequest
	(*DeleteSellerResponse)(nil),  // 10: marketplace.v1.DeleteSellerResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_seller_proto_depIdxs = []int32{
	11, // 0: marketplace.v1.Seller.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: marketplace.v1.Seller.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: marketplace.v1.CreateSellerResponse.seller:type_name -> marketplace.v1.Seller
	0,  // 3: marketplace.v1.GetSellerResponse.seller:type_name -> marketplace.v1.Seller
	0,  // 4: marketplace.v1.ListSellersResponse.sellers:type_name -> marketplace.v1.Seller
	0,  // 5: marketplace.v1.UpdateSellerResponse.seller:type_name -> marketplace.v1.Seller
	1,  // 6: marketplace.v1.SellerService.CreateSeller:input_type -> marketplace.v1.CreateSellerRequest
	3,  // 7: marketplace.v1.SellerService.GetSeller:input_type -> marketplace.v1.GetSellerRequest
	5,  // 8: marketplace.v1.SellerService.ListSellers:input_type -> marketplace.v1.ListSellersRequest
	7,  // 9: marketplace.v1.SellerService.UpdateSeller:input_type -> marketplace.v1.UpdateSellerRequest
	9,  // 10: marketplace.v1.SellerService.DeleteSeller:input_type -> marketplace.v1.DeleteSellerRequest
	2,  // 11: marketplace.v1.SellerService.CreateSeller:output_type -> marketplace.v1.CreateSellerResponse
	4,  // 12: marketplace.v1.SellerService.GetSeller:output_type -> marketplace.v1.GetSellerResponse
	6,  // 13: marketplace.v1.SellerService.ListSellers:output_type -> marketplace.v1.ListSellersResponse
	8,  // 14: marketplace.v1.SellerService.UpdateSeller:output_type -> marketplace.v1.UpdateSellerResponse
	10, // 15: marketplace.v1.SellerService.DeleteSeller:output_type -> marketplace.v1.DeleteSellerResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_seller_proto_init() }
func file_proto_seller_proto_init() {
	if File_proto_seller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_seller_proto_rawDesc), len(file_proto_seller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_seller_proto_goTypes,
		DependencyIndexes: file_proto_seller_proto_depIdxs,
		MessageInfos:      file_proto_seller_proto_msgTypes,
	}.Build()
	File_proto_seller_proto = out.File
	file_proto_seller_proto_goTypes = nil
	file_proto_seller_proto_depIdxs = nil
}
