apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespaces
  - ../../base/namespaces

  # Databases
  - postgres

  # Messaging
  - kafka

  # Cache
  - redis

  # Ingress Controller
  - ingress-controller

  # API Gateway (REST)
  - api-gateway

  # GraphQL Gateway (Apollo Router)
  - graphql

  # Monitoring Stack
  - monitoring
