apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespaces
  - ../../base/namespaces

  # Databases
  - postgres

  # Messaging
  - kafka

  # Cache
  - redis

  # Ingress Controller
  - ingress-controller

  # Gateway Tier (API Gateway + Apollo Router + Ingress)
  - gateway

  # Monitoring Stack
  - monitoring
