apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  podSelector:
    matchLabels:
      app: notification-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8086
        - protocol: TCP
          port: 8087
