apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: notification-service
automountServiceAccountToken: true
