apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8086
      targetPort: http
      protocol: TCP
    - name: sse
      port: 9086
      targetPort: sse
      protocol: TCP
  sessionAffinity: None
