// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/raphaeldiscky/go-micro-commerce/order-service/internal/constant"
	"github.com/shopspring/decimal"
)

type CreateOrderInput struct {
	IdempotencyKey uuid.UUID               `json:"idempotencyKey"`
	Items          []*CreateOrderItemInput `json:"items"`
	Shipping       *ShippingInput          `json:"shipping"`
	PaymentMethod  constant.PaymentMethod  `json:"paymentMethod"`
	PaymentGateway constant.PaymentGateway `json:"paymentGateway"`
	Currency       string                  `json:"currency"`
}

type CreateOrderItemInput struct {
	ProductID uuid.UUID `json:"productId"`
	Quantity  int       `json:"quantity"`
}

type DimensionsInput struct {
	Length decimal.Decimal `json:"length"`
	Height decimal.Decimal `json:"height"`
	Width  decimal.Decimal `json:"width"`
	Unit   string          `json:"unit"`
}

type FromAddressInput struct {
	City       string `json:"city"`
	State      string `json:"state"`
	PostalCode string `json:"postalCode"`
	Country    string `json:"country"`
}

type Mutation struct {
}

type Order struct {
	ID             uuid.UUID               `json:"id"`
	IdempotencyKey uuid.UUID               `json:"idempotencyKey"`
	CustomerID     uuid.UUID               `json:"customerId"`
	Status         constant.OrderStatus    `json:"status"`
	Currency       string                  `json:"currency"`
	PaymentGateway constant.PaymentGateway `json:"paymentGateway"`
	PaymentMethod  constant.PaymentMethod  `json:"paymentMethod"`
	ShippingCost   decimal.Decimal         `json:"shippingCost"`
	Subtotal       decimal.Decimal         `json:"subtotal"`
	TotalPrice     decimal.Decimal         `json:"totalPrice"`
	TotalTax       decimal.Decimal         `json:"totalTax"`
	TotalDiscount  decimal.Decimal         `json:"totalDiscount"`
	Items          []*OrderItem            `json:"items"`
	CreatedAt      time.Time               `json:"createdAt"`
	UpdatedAt      time.Time               `json:"updatedAt"`
}

type OrderConnection struct {
	Edges    []*OrderEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type OrderEdge struct {
	Node   *Order `json:"node"`
	Cursor string `json:"cursor"`
}

type OrderItem struct {
	ID            uuid.UUID       `json:"id"`
	OrderID       uuid.UUID       `json:"orderId"`
	ProductID     uuid.UUID       `json:"productId"`
	Quantity      int             `json:"quantity"`
	UnitPrice     decimal.Decimal `json:"unitPrice"`
	TotalPrice    decimal.Decimal `json:"totalPrice"`
	TaxRate       decimal.Decimal `json:"taxRate"`
	TotalTax      decimal.Decimal `json:"totalTax"`
	TotalDiscount decimal.Decimal `json:"totalDiscount"`
	CreatedAt     time.Time       `json:"createdAt"`
	UpdatedAt     time.Time       `json:"updatedAt"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type ShippingInput struct {
	CarrierID   string            `json:"carrierId"`
	FromAddress *FromAddressInput `json:"fromAddress"`
	ToAddress   *ToAddressInput   `json:"toAddress"`
	WeightKg    decimal.Decimal   `json:"weightKg"`
	Dimensions  *DimensionsInput  `json:"dimensions"`
}

type ToAddressInput struct {
	City       string `json:"city"`
	State      string `json:"state"`
	PostalCode string `json:"postalCode"`
	Country    string `json:"country"`
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
