services:
  auth-service:
    build:
      context: ../..
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    volumes:
      - ../../auth-service/.env:/app/.env:ro
    restart: unless-stopped
    depends_on:
      postgres-auth:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      consul:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - go-micro-template
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8081/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  product-service:
    build:
      context: ../..
      dockerfile: product-service/Dockerfile
    container_name: product-service
    volumes:
      - ../../product-service/.env:/app/.env:ro
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      postgres-product:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - go-micro-template
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8082/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  order-service:
    build:
      context: ../..
      dockerfile: order-service/Dockerfile
    container_name: order-service
    restart: unless-stopped
    volumes:
      - ../../order-service/.env:/app/.env:ro
    ports:
      - "8083:8083"
    depends_on:
      postgres-order:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - go-micro-template
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8083/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  payment-service:
    build:
      context: ../..
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    volumes:
      - ../../payment-service/.env:/app/.env:ro
    restart: unless-stopped
    ports:
      - "8084:8084"
    depends_on:
      postgres-payment:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - go-micro-template
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8084/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  notification-service:
    build:
      context: ../..
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    volumes:
      - ../../notification-service/.env:/app/.env:ro
    restart: unless-stopped
    ports:
      - "8085:8085"
    depends_on:
      mailhog:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - go-micro-template
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8085/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build:
      context: ../..
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    volumes:
      - ../../api-gateway/.env:/app/.env:ro
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - go-micro-template
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  go-micro-template:
    name: go-micro-template
    external: true
