services:
  graphql-gateway:
    build:
      context: ../..
      dockerfile: graphql-gateway/Dockerfile
    container_name: graphql-gateway
    ports:
      - "4000:4000" # GraphQL endpoint
      - "4088:4088" # Health check
      - "9091:9091" # Prometheus metrics
    networks:
      - go-micro-commerce
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APOLLO_ROUTER_SUPERGRAPH_PATH=/app/supergraph-schema.graphql
      - APOLLO_ROUTER_CONFIG_PATH=/app/router.yaml
      - RUST_LOG=info
      - APOLLO_ELV2_LICENSE=accept
    # depends_on:
    #   - auth-service
    #   - chat-service
    #   - otel-collector
    restart: unless-stopped

networks:
  go-micro-commerce:
    name: go-micro-commerce
    external: true
