# Local infrastructure services
include:
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - temporal.yaml
  - elasticsearch.yaml
  - monitoring.yaml
  - vault.yaml
  - dev-tools.yaml
  - api-gateway.yaml
  - graphql-gateway.yaml
  # - dev.yaml

networks:
  go-micro-commerce:
    name: go-micro-commerce
    external: true
