# Local infrastructure services
include:
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - monitoring.yaml
  - security.yaml
  - dev-tools.yaml
  - api-gateway.yaml
  - dev.yaml

networks:
  go-micro-template:
    name: go-micro-template
    external: true
