services:
  postgres-auth:
    image: postgres:17.5-alpine
    container_name: postgres-auth
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "15431:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-product:
    image: postgres:17.5-alpine
    container_name: postgres-product
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_db
    ports:
      - "15432:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-order:
    image: postgres:17.5-alpine
    container_name: postgres-order
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_db
    ports:
      - "15433:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-payment:
    image: postgres:17.5-alpine
    container_name: postgres-payment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_db
    ports:
      - "15434:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-fulfillment:
    image: postgres:17.5-alpine
    container_name: postgres-fulfillment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fulfillment_db
    ports:
      - "15435:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_fulfillment_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-notification:
    image: postgres:17.5-alpine
    container_name: postgres-notification
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notification_db
    ports:
      - "15436:5432"
    networks:
      - go-micro-commerce
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-search:
    image: postgres:17.5-alpine
    container_name: postgres-search
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=search_db
    ports:
      - "15437:5432"
    networks:
      - go-micro-commerce
    volumes:
      - postgres_search_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_auth_data:
  postgres_product_data:
  postgres_order_data:
  postgres_payment_data:
  postgres_fulfillment_data:
  postgres_notification_data:
  postgres_search_data:

networks:
  go-micro-commerce:
    name: go-micro-commerce
    external: true
