services:
  postgres-auth:
    image: postgres:17.5-alpine
    container_name: postgres-auth
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "15432:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-auth_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-product:
    image: postgres:17.5-alpine
    container_name: postgres-product
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "25432:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-product_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-order:
    image: postgres:17.5-alpine
    container_name: postgres-order
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "35432:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-order_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-payment:
    image: postgres:17.5-alpine
    container_name: postgres-payment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "45432:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-payment_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres-fulfillment:
    image: postgres:17.5-alpine
    container_name: postgres-fulfillment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "55432:5432"
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-fulfillment_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

volumes:
  postgres-auth_data:
  postgres-product_data:
  postgres-order_data:
  postgres-payment_data:

networks:
  go-micro-commerce:
    name: go-micro-commerce
    external: true
