services:
  # redis-1 is now designated as the cluster creator.
  # It will wait for all other nodes to be healthy before initializing the cluster.
  redis-1:
    image: "bitnami/redis-cluster:8.2.1"
    container_name: redis-1
    ports:
      - 6379:6379 # Use the default port for the creator for easier access
      - 16379:16379
    environment:
      - REDIS_PASSWORD=supersecret
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=redis-1 redis-2 redis-3 redis-4 redis-5 redis-6
      - REDIS_CLUSTER_CREATOR=yes # This node will create the cluster
    networks:
      - go-micro-commerce
    volumes:
      - redis_1_data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "supersecret", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
  redis-2: &redis-node-common
    image: "bitnami/redis-cluster:8.2.1"
    container_name: redis-2
    environment:
      - REDIS_PASSWORD=supersecret
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=redis-1 redis-2 redis-3 redis-4 redis-5 redis-6
    networks:
      - go-micro-commerce
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "supersecret", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - redis_2_data:/bitnami/redis/data
  redis-3:
    !!merge <<: *redis-node-common
    container_name: redis-3
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - redis_3_data:/bitnami/redis/data
  redis-4:
    !!merge <<: *redis-node-common
    container_name: redis-4
    ports:
      - "6382:6379"
      - "16382:16379"
    volumes:
      - redis_4_data:/bitnami/redis/data
  redis-5:
    !!merge <<: *redis-node-common
    container_name: redis-5
    ports:
      - "6383:6379"
      - "16383:16379"
    volumes:
      - redis_5_data:/bitnami/redis/data
  redis-6:
    !!merge <<: *redis-node-common
    container_name: redis-6
    ports:
      - "6384:6379"
      - "16384:16379"
    volumes:
      - redis_6_data:/bitnami/redis/data
  redis-insight:
    image: redis/redisinsight:2.70
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/db
    networks:
      - go-micro-commerce
    depends_on:
      redis-1:
        condition: service_healthy
volumes:
  redis_1_data:
  redis_2_data:
  redis_3_data:
  redis_4_data:
  redis_5_data:
  redis_6_data:
  redis_insight_data:
networks:
  go-micro-commerce:
    name: go-micro-commerce
    external: true
