/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as FeaturesProductsIndexRouteImport } from './routes/features/products/index'
import { Route as FeaturesCheckoutIndexRouteImport } from './routes/features/checkout/index'
import { Route as FeaturesChatIndexRouteImport } from './routes/features/chat/index'
import { Route as FeaturesAccountIndexRouteImport } from './routes/features/account/index'
import { Route as FeaturesCheckoutCheckoutIdRouteImport } from './routes/features/checkout/$checkoutId'
import { Route as FeaturesChatConversationIdRouteImport } from './routes/features/chat/$conversationId'
import { Route as FeaturesAccountAccountIdRouteImport } from './routes/features/account/$accountId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesProductsIndexRoute = FeaturesProductsIndexRouteImport.update({
  id: '/features/products/',
  path: '/features/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCheckoutIndexRoute = FeaturesCheckoutIndexRouteImport.update({
  id: '/features/checkout/',
  path: '/features/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesChatIndexRoute = FeaturesChatIndexRouteImport.update({
  id: '/features/chat/',
  path: '/features/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesAccountIndexRoute = FeaturesAccountIndexRouteImport.update({
  id: '/features/account/',
  path: '/features/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCheckoutCheckoutIdRoute =
  FeaturesCheckoutCheckoutIdRouteImport.update({
    id: '/features/checkout/$checkoutId',
    path: '/features/checkout/$checkoutId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesChatConversationIdRoute =
  FeaturesChatConversationIdRouteImport.update({
    id: '/features/chat/$conversationId',
    path: '/features/chat/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesAccountAccountIdRoute =
  FeaturesAccountAccountIdRouteImport.update({
    id: '/features/account/$accountId',
    path: '/features/account/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/features/account/$accountId': typeof FeaturesAccountAccountIdRoute
  '/features/chat/$conversationId': typeof FeaturesChatConversationIdRoute
  '/features/checkout/$checkoutId': typeof FeaturesCheckoutCheckoutIdRoute
  '/features/account': typeof FeaturesAccountIndexRoute
  '/features/chat': typeof FeaturesChatIndexRoute
  '/features/checkout': typeof FeaturesCheckoutIndexRoute
  '/features/products': typeof FeaturesProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/features/account/$accountId': typeof FeaturesAccountAccountIdRoute
  '/features/chat/$conversationId': typeof FeaturesChatConversationIdRoute
  '/features/checkout/$checkoutId': typeof FeaturesCheckoutCheckoutIdRoute
  '/features/account': typeof FeaturesAccountIndexRoute
  '/features/chat': typeof FeaturesChatIndexRoute
  '/features/checkout': typeof FeaturesCheckoutIndexRoute
  '/features/products': typeof FeaturesProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/features/account/$accountId': typeof FeaturesAccountAccountIdRoute
  '/features/chat/$conversationId': typeof FeaturesChatConversationIdRoute
  '/features/checkout/$checkoutId': typeof FeaturesCheckoutCheckoutIdRoute
  '/features/account/': typeof FeaturesAccountIndexRoute
  '/features/chat/': typeof FeaturesChatIndexRoute
  '/features/checkout/': typeof FeaturesCheckoutIndexRoute
  '/features/products/': typeof FeaturesProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/services'
    | '/auth/login'
    | '/auth/register'
    | '/features/account/$accountId'
    | '/features/chat/$conversationId'
    | '/features/checkout/$checkoutId'
    | '/features/account'
    | '/features/chat'
    | '/features/checkout'
    | '/features/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/services'
    | '/auth/login'
    | '/auth/register'
    | '/features/account/$accountId'
    | '/features/chat/$conversationId'
    | '/features/checkout/$checkoutId'
    | '/features/account'
    | '/features/chat'
    | '/features/checkout'
    | '/features/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/services'
    | '/auth/login'
    | '/auth/register'
    | '/features/account/$accountId'
    | '/features/chat/$conversationId'
    | '/features/checkout/$checkoutId'
    | '/features/account/'
    | '/features/chat/'
    | '/features/checkout/'
    | '/features/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ServicesRoute: typeof ServicesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  FeaturesAccountAccountIdRoute: typeof FeaturesAccountAccountIdRoute
  FeaturesChatConversationIdRoute: typeof FeaturesChatConversationIdRoute
  FeaturesCheckoutCheckoutIdRoute: typeof FeaturesCheckoutCheckoutIdRoute
  FeaturesAccountIndexRoute: typeof FeaturesAccountIndexRoute
  FeaturesChatIndexRoute: typeof FeaturesChatIndexRoute
  FeaturesCheckoutIndexRoute: typeof FeaturesCheckoutIndexRoute
  FeaturesProductsIndexRoute: typeof FeaturesProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/products/': {
      id: '/features/products/'
      path: '/features/products'
      fullPath: '/features/products'
      preLoaderRoute: typeof FeaturesProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/checkout/': {
      id: '/features/checkout/'
      path: '/features/checkout'
      fullPath: '/features/checkout'
      preLoaderRoute: typeof FeaturesCheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/chat/': {
      id: '/features/chat/'
      path: '/features/chat'
      fullPath: '/features/chat'
      preLoaderRoute: typeof FeaturesChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/account/': {
      id: '/features/account/'
      path: '/features/account'
      fullPath: '/features/account'
      preLoaderRoute: typeof FeaturesAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/checkout/$checkoutId': {
      id: '/features/checkout/$checkoutId'
      path: '/features/checkout/$checkoutId'
      fullPath: '/features/checkout/$checkoutId'
      preLoaderRoute: typeof FeaturesCheckoutCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/chat/$conversationId': {
      id: '/features/chat/$conversationId'
      path: '/features/chat/$conversationId'
      fullPath: '/features/chat/$conversationId'
      preLoaderRoute: typeof FeaturesChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/account/$accountId': {
      id: '/features/account/$accountId'
      path: '/features/account/$accountId'
      fullPath: '/features/account/$accountId'
      preLoaderRoute: typeof FeaturesAccountAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ServicesRoute: ServicesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  FeaturesAccountAccountIdRoute: FeaturesAccountAccountIdRoute,
  FeaturesChatConversationIdRoute: FeaturesChatConversationIdRoute,
  FeaturesCheckoutCheckoutIdRoute: FeaturesCheckoutCheckoutIdRoute,
  FeaturesAccountIndexRoute: FeaturesAccountIndexRoute,
  FeaturesChatIndexRoute: FeaturesChatIndexRoute,
  FeaturesCheckoutIndexRoute: FeaturesCheckoutIndexRoute,
  FeaturesProductsIndexRoute: FeaturesProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
