// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: chat/conversation/v1/conversation.proto

package conversationv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConversationStatus represents the status of a chat conversation
type ConversationStatus int32

const (
	ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED ConversationStatus = 0
	ConversationStatus_CONVERSATION_STATUS_WAITING     ConversationStatus = 1 // Waiting for admin assignment
	ConversationStatus_CONVERSATION_STATUS_ACTIVE      ConversationStatus = 2 // Active conversation
	ConversationStatus_CONVERSATION_STATUS_ENDED       ConversationStatus = 3 // Ended conversation
	ConversationStatus_CONVERSATION_STATUS_TRANSFERRED ConversationStatus = 4 // Transferred to another admin
)

// Enum value maps for ConversationStatus.
var (
	ConversationStatus_name = map[int32]string{
		0: "CONVERSATION_STATUS_UNSPECIFIED",
		1: "CONVERSATION_STATUS_WAITING",
		2: "CONVERSATION_STATUS_ACTIVE",
		3: "CONVERSATION_STATUS_ENDED",
		4: "CONVERSATION_STATUS_TRANSFERRED",
	}
	ConversationStatus_value = map[string]int32{
		"CONVERSATION_STATUS_UNSPECIFIED": 0,
		"CONVERSATION_STATUS_WAITING":     1,
		"CONVERSATION_STATUS_ACTIVE":      2,
		"CONVERSATION_STATUS_ENDED":       3,
		"CONVERSATION_STATUS_TRANSFERRED": 4,
	}
)

func (x ConversationStatus) Enum() *ConversationStatus {
	p := new(ConversationStatus)
	*p = x
	return p
}

func (x ConversationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_conversation_v1_conversation_proto_enumTypes[0].Descriptor()
}

func (ConversationStatus) Type() protoreflect.EnumType {
	return &file_chat_conversation_v1_conversation_proto_enumTypes[0]
}

func (x ConversationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationStatus.Descriptor instead.
func (ConversationStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{0}
}

// UserType represents the type of user in the chat system
type UserType int32

const (
	UserType_USER_TYPE_UNSPECIFIED UserType = 0
	UserType_USER_TYPE_USER        UserType = 1 // Regular user/customer
	UserType_USER_TYPE_ADMIN       UserType = 2 // Admin/support agent
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER_TYPE_UNSPECIFIED",
		1: "USER_TYPE_USER",
		2: "USER_TYPE_ADMIN",
	}
	UserType_value = map[string]int32{
		"USER_TYPE_UNSPECIFIED": 0,
		"USER_TYPE_USER":        1,
		"USER_TYPE_ADMIN":       2,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_conversation_v1_conversation_proto_enumTypes[1].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_chat_conversation_v1_conversation_proto_enumTypes[1]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{1}
}

// ParticipantRole represents the role of a participant in a conversation
type ParticipantRole int32

const (
	ParticipantRole_PARTICIPANT_ROLE_UNSPECIFIED ParticipantRole = 0
	ParticipantRole_PARTICIPANT_ROLE_PARTICIPANT ParticipantRole = 1 // Regular participant
	ParticipantRole_PARTICIPANT_ROLE_MODERATOR   ParticipantRole = 2 // Moderator with elevated permissions
	ParticipantRole_PARTICIPANT_ROLE_OBSERVER    ParticipantRole = 3 // Observer with read-only access
)

// Enum value maps for ParticipantRole.
var (
	ParticipantRole_name = map[int32]string{
		0: "PARTICIPANT_ROLE_UNSPECIFIED",
		1: "PARTICIPANT_ROLE_PARTICIPANT",
		2: "PARTICIPANT_ROLE_MODERATOR",
		3: "PARTICIPANT_ROLE_OBSERVER",
	}
	ParticipantRole_value = map[string]int32{
		"PARTICIPANT_ROLE_UNSPECIFIED": 0,
		"PARTICIPANT_ROLE_PARTICIPANT": 1,
		"PARTICIPANT_ROLE_MODERATOR":   2,
		"PARTICIPANT_ROLE_OBSERVER":    3,
	}
)

func (x ParticipantRole) Enum() *ParticipantRole {
	p := new(ParticipantRole)
	*p = x
	return p
}

func (x ParticipantRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_conversation_v1_conversation_proto_enumTypes[2].Descriptor()
}

func (ParticipantRole) Type() protoreflect.EnumType {
	return &file_chat_conversation_v1_conversation_proto_enumTypes[2]
}

func (x ParticipantRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantRole.Descriptor instead.
func (ParticipantRole) EnumDescriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{2}
}

// GetUserConversationsRequest represents the request to get user conversations
type GetUserConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      UserType               `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=chat.conversation.v1.UserType" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConversationsRequest) Reset() {
	*x = GetUserConversationsRequest{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConversationsRequest) ProtoMessage() {}

func (x *GetUserConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConversationsRequest.ProtoReflect.Descriptor instead.
func (*GetUserConversationsRequest) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserConversationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserConversationsRequest) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

// GetUserConversationsResponse represents the response for user conversations
type GetUserConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConversationsResponse) Reset() {
	*x = GetUserConversationsResponse{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConversationsResponse) ProtoMessage() {}

func (x *GetUserConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConversationsResponse.ProtoReflect.Descriptor instead.
func (*GetUserConversationsResponse) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

// CreateConversationRequest represents the request to create a new conversation
type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *string                `protobuf:"bytes,1,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateConversationRequest) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *CreateConversationRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// CreateConversationResponse represents the response for conversation creation
type CreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

// GetConversationRequest represents the request to get a conversation
type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetConversationResponse represents the response for getting a conversation
type GetConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *GetConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

// JoinConversationRequest represents the request to join a conversation
type JoinConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType       UserType               `protobuf:"varint,3,opt,name=user_type,json=userType,proto3,enum=chat.conversation.v1.UserType" json:"user_type,omitempty"`
	Role           ParticipantRole        `protobuf:"varint,4,opt,name=role,proto3,enum=chat.conversation.v1.ParticipantRole" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinConversationRequest) Reset() {
	*x = JoinConversationRequest{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinConversationRequest) ProtoMessage() {}

func (x *JoinConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinConversationRequest.ProtoReflect.Descriptor instead.
func (*JoinConversationRequest) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *JoinConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *JoinConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinConversationRequest) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

func (x *JoinConversationRequest) GetRole() ParticipantRole {
	if x != nil {
		return x.Role
	}
	return ParticipantRole_PARTICIPANT_ROLE_UNSPECIFIED
}

// JoinConversationResponse represents the response for joining a conversation
type JoinConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participant   *Participant           `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinConversationResponse) Reset() {
	*x = JoinConversationResponse{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinConversationResponse) ProtoMessage() {}

func (x *JoinConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinConversationResponse.ProtoReflect.Descriptor instead.
func (*JoinConversationResponse) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *JoinConversationResponse) GetParticipant() *Participant {
	if x != nil {
		return x.Participant
	}
	return nil
}

// UpdateConversationStatusRequest represents the request to update conversation status
type UpdateConversationStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Status         ConversationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=chat.conversation.v1.ConversationStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConversationStatusRequest) Reset() {
	*x = UpdateConversationStatusRequest{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationStatusRequest) ProtoMessage() {}

func (x *UpdateConversationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationStatusRequest) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateConversationStatusRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateConversationStatusRequest) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED
}

// UpdateConversationStatusResponse represents the response for updating conversation status
type UpdateConversationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationStatusResponse) Reset() {
	*x = UpdateConversationStatusResponse{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationStatusResponse) ProtoMessage() {}

func (x *UpdateConversationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateConversationStatusResponse) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateConversationStatusResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

// Conversation represents a chat conversation
type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        ConversationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=chat.conversation.v1.ConversationStatus" json:"status,omitempty"`
	Subject       *string                `protobuf:"bytes,3,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED
}

func (x *Conversation) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *Conversation) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Conversation) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Conversation) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

// Participant represents a conversation participant
type Participant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType       UserType               `protobuf:"varint,4,opt,name=user_type,json=userType,proto3,enum=chat.conversation.v1.UserType" json:"user_type,omitempty"`
	Role           ParticipantRole        `protobuf:"varint,5,opt,name=role,proto3,enum=chat.conversation.v1.ParticipantRole" json:"role,omitempty"`
	JoinedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=left_at,json=leftAt,proto3,oneof" json:"left_at,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_chat_conversation_v1_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_chat_conversation_v1_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *Participant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Participant) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Participant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Participant) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

func (x *Participant) GetRole() ParticipantRole {
	if x != nil {
		return x.Role
	}
	return ParticipantRole_PARTICIPANT_ROLE_UNSPECIFIED
}

func (x *Participant) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Participant) GetLeftAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeftAt
	}
	return nil
}

func (x *Participant) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_chat_conversation_v1_conversation_proto protoreflect.FileDescriptor

const file_chat_conversation_v1_conversation_proto_rawDesc = "" +
	"\n" +
	"'chat/conversation/v1/conversation.proto\x12\x14chat.conversation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bbuf/validate/validate.proto\"}\n" +
	"\x1bGetUserConversationsRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12;\n" +
	"\tuser_type\x18\x02 \x01(\x0e2\x1e.chat.conversation.v1.UserTypeR\buserType\"h\n" +
	"\x1cGetUserConversationsResponse\x12H\n" +
	"\rconversations\x18\x01 \x03(\v2\".chat.conversation.v1.ConversationR\rconversations\"w\n" +
	"\x19CreateConversationRequest\x12'\n" +
	"\asubject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x00R\asubject\x88\x01\x01\x12%\n" +
	"\bpriority\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x04(\x01R\bpriorityB\n" +
	"\n" +
	"\b_subject\"d\n" +
	"\x1aCreateConversationResponse\x12F\n" +
	"\fconversation\x18\x01 \x01(\v2\".chat.conversation.v1.ConversationR\fconversation\"n\n" +
	"\x16GetConversationRequest\x121\n" +
	"\x0fconversation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0econversationId\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"a\n" +
	"\x17GetConversationResponse\x12F\n" +
	"\fconversation\x18\x01 \x01(\v2\".chat.conversation.v1.ConversationR\fconversation\"\xe7\x01\n" +
	"\x17JoinConversationRequest\x121\n" +
	"\x0fconversation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0econversationId\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12;\n" +
	"\tuser_type\x18\x03 \x01(\x0e2\x1e.chat.conversation.v1.UserTypeR\buserType\x129\n" +
	"\x04role\x18\x04 \x01(\x0e2%.chat.conversation.v1.ParticipantRoleR\x04role\"_\n" +
	"\x18JoinConversationResponse\x12C\n" +
	"\vparticipant\x18\x01 \x01(\v2!.chat.conversation.v1.ParticipantR\vparticipant\"\x96\x01\n" +
	"\x1fUpdateConversationStatusRequest\x121\n" +
	"\x0fconversation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0econversationId\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.chat.conversation.v1.ConversationStatusR\x06status\"j\n" +
	" UpdateConversationStatusResponse\x12F\n" +
	"\fconversation\x18\x01 \x01(\v2\".chat.conversation.v1.ConversationR\fconversation\"\xb0\x03\n" +
	"\fConversation\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.chat.conversation.v1.ConversationStatusR\x06status\x12\x1d\n" +
	"\asubject\x18\x03 \x01(\tH\x00R\asubject\x88\x01\x01\x12%\n" +
	"\bpriority\x18\x04 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x04(\x01R\bpriority\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12:\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendedAt\x88\x01\x01B\n" +
	"\n" +
	"\b_subjectB\v\n" +
	"\t_ended_at\"\x91\x03\n" +
	"\vParticipant\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x121\n" +
	"\x0fconversation_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0econversationId\x12!\n" +
	"\auser_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12;\n" +
	"\tuser_type\x18\x04 \x01(\x0e2\x1e.chat.conversation.v1.UserTypeR\buserType\x129\n" +
	"\x04role\x18\x05 \x01(\x0e2%.chat.conversation.v1.ParticipantRoleR\x04role\x127\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x128\n" +
	"\aleft_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x06leftAt\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActiveB\n" +
	"\n" +
	"\b_left_at*\xbe\x01\n" +
	"\x12ConversationStatus\x12#\n" +
	"\x1fCONVERSATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONVERSATION_STATUS_WAITING\x10\x01\x12\x1e\n" +
	"\x1aCONVERSATION_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19CONVERSATION_STATUS_ENDED\x10\x03\x12#\n" +
	"\x1fCONVERSATION_STATUS_TRANSFERRED\x10\x04*N\n" +
	"\bUserType\x12\x19\n" +
	"\x15USER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_TYPE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_TYPE_ADMIN\x10\x02*\x94\x01\n" +
	"\x0fParticipantRole\x12 \n" +
	"\x1cPARTICIPANT_ROLE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPARTICIPANT_ROLE_PARTICIPANT\x10\x01\x12\x1e\n" +
	"\x1aPARTICIPANT_ROLE_MODERATOR\x10\x02\x12\x1d\n" +
	"\x19PARTICIPANT_ROLE_OBSERVER\x10\x032\xfc\x04\n" +
	"\x13ConversationService\x12}\n" +
	"\x14GetUserConversations\x121.chat.conversation.v1.GetUserConversationsRequest\x1a2.chat.conversation.v1.GetUserConversationsResponse\x12w\n" +
	"\x12CreateConversation\x12/.chat.conversation.v1.CreateConversationRequest\x1a0.chat.conversation.v1.CreateConversationResponse\x12n\n" +
	"\x0fGetConversation\x12,.chat.conversation.v1.GetConversationRequest\x1a-.chat.conversation.v1.GetConversationResponse\x12\x89\x01\n" +
	"\x18UpdateConversationStatus\x125.chat.conversation.v1.UpdateConversationStatusRequest\x1a6.chat.conversation.v1.UpdateConversationStatusResponse\x12q\n" +
	"\x10JoinConversation\x12-.chat.conversation.v1.JoinConversationRequest\x1a..chat.conversation.v1.JoinConversationResponseB\xf5\x01\n" +
	"\x18com.chat.conversation.v1B\x11ConversationProtoP\x01ZTgithub.com/raphaeldiscky/go-micro-commerce/proto/chat/conversation/v1;conversationv1\xa2\x02\x03CCX\xaa\x02\x14Chat.Conversation.V1\xca\x02\x14Chat\\Conversation\\V1\xe2\x02 Chat\\Conversation\\V1\\GPBMetadata\xea\x02\x16Chat::Conversation::V1b\x06proto3"

var (
	file_chat_conversation_v1_conversation_proto_rawDescOnce sync.Once
	file_chat_conversation_v1_conversation_proto_rawDescData []byte
)

func file_chat_conversation_v1_conversation_proto_rawDescGZIP() []byte {
	file_chat_conversation_v1_conversation_proto_rawDescOnce.Do(func() {
		file_chat_conversation_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_conversation_v1_conversation_proto_rawDesc), len(file_chat_conversation_v1_conversation_proto_rawDesc)))
	})
	return file_chat_conversation_v1_conversation_proto_rawDescData
}

var file_chat_conversation_v1_conversation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_chat_conversation_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chat_conversation_v1_conversation_proto_goTypes = []any{
	(ConversationStatus)(0),                  // 0: chat.conversation.v1.ConversationStatus
	(UserType)(0),                            // 1: chat.conversation.v1.UserType
	(ParticipantRole)(0),                     // 2: chat.conversation.v1.ParticipantRole
	(*GetUserConversationsRequest)(nil),      // 3: chat.conversation.v1.GetUserConversationsRequest
	(*GetUserConversationsResponse)(nil),     // 4: chat.conversation.v1.GetUserConversationsResponse
	(*CreateConversationRequest)(nil),        // 5: chat.conversation.v1.CreateConversationRequest
	(*CreateConversationResponse)(nil),       // 6: chat.conversation.v1.CreateConversationResponse
	(*GetConversationRequest)(nil),           // 7: chat.conversation.v1.GetConversationRequest
	(*GetConversationResponse)(nil),          // 8: chat.conversation.v1.GetConversationResponse
	(*JoinConversationRequest)(nil),          // 9: chat.conversation.v1.JoinConversationRequest
	(*JoinConversationResponse)(nil),         // 10: chat.conversation.v1.JoinConversationResponse
	(*UpdateConversationStatusRequest)(nil),  // 11: chat.conversation.v1.UpdateConversationStatusRequest
	(*UpdateConversationStatusResponse)(nil), // 12: chat.conversation.v1.UpdateConversationStatusResponse
	(*Conversation)(nil),                     // 13: chat.conversation.v1.Conversation
	(*Participant)(nil),                      // 14: chat.conversation.v1.Participant
	(*structpb.Struct)(nil),                  // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),            // 16: google.protobuf.Timestamp
}
var file_chat_conversation_v1_conversation_proto_depIdxs = []int32{
	1,  // 0: chat.conversation.v1.GetUserConversationsRequest.user_type:type_name -> chat.conversation.v1.UserType
	13, // 1: chat.conversation.v1.GetUserConversationsResponse.conversations:type_name -> chat.conversation.v1.Conversation
	13, // 2: chat.conversation.v1.CreateConversationResponse.conversation:type_name -> chat.conversation.v1.Conversation
	13, // 3: chat.conversation.v1.GetConversationResponse.conversation:type_name -> chat.conversation.v1.Conversation
	1,  // 4: chat.conversation.v1.JoinConversationRequest.user_type:type_name -> chat.conversation.v1.UserType
	2,  // 5: chat.conversation.v1.JoinConversationRequest.role:type_name -> chat.conversation.v1.ParticipantRole
	14, // 6: chat.conversation.v1.JoinConversationResponse.participant:type_name -> chat.conversation.v1.Participant
	0,  // 7: chat.conversation.v1.UpdateConversationStatusRequest.status:type_name -> chat.conversation.v1.ConversationStatus
	13, // 8: chat.conversation.v1.UpdateConversationStatusResponse.conversation:type_name -> chat.conversation.v1.Conversation
	0,  // 9: chat.conversation.v1.Conversation.status:type_name -> chat.conversation.v1.ConversationStatus
	15, // 10: chat.conversation.v1.Conversation.metadata:type_name -> google.protobuf.Struct
	16, // 11: chat.conversation.v1.Conversation.created_at:type_name -> google.protobuf.Timestamp
	16, // 12: chat.conversation.v1.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	16, // 13: chat.conversation.v1.Conversation.ended_at:type_name -> google.protobuf.Timestamp
	1,  // 14: chat.conversation.v1.Participant.user_type:type_name -> chat.conversation.v1.UserType
	2,  // 15: chat.conversation.v1.Participant.role:type_name -> chat.conversation.v1.ParticipantRole
	16, // 16: chat.conversation.v1.Participant.joined_at:type_name -> google.protobuf.Timestamp
	16, // 17: chat.conversation.v1.Participant.left_at:type_name -> google.protobuf.Timestamp
	3,  // 18: chat.conversation.v1.ConversationService.GetUserConversations:input_type -> chat.conversation.v1.GetUserConversationsRequest
	5,  // 19: chat.conversation.v1.ConversationService.CreateConversation:input_type -> chat.conversation.v1.CreateConversationRequest
	7,  // 20: chat.conversation.v1.ConversationService.GetConversation:input_type -> chat.conversation.v1.GetConversationRequest
	11, // 21: chat.conversation.v1.ConversationService.UpdateConversationStatus:input_type -> chat.conversation.v1.UpdateConversationStatusRequest
	9,  // 22: chat.conversation.v1.ConversationService.JoinConversation:input_type -> chat.conversation.v1.JoinConversationRequest
	4,  // 23: chat.conversation.v1.ConversationService.GetUserConversations:output_type -> chat.conversation.v1.GetUserConversationsResponse
	6,  // 24: chat.conversation.v1.ConversationService.CreateConversation:output_type -> chat.conversation.v1.CreateConversationResponse
	8,  // 25: chat.conversation.v1.ConversationService.GetConversation:output_type -> chat.conversation.v1.GetConversationResponse
	12, // 26: chat.conversation.v1.ConversationService.UpdateConversationStatus:output_type -> chat.conversation.v1.UpdateConversationStatusResponse
	10, // 27: chat.conversation.v1.ConversationService.JoinConversation:output_type -> chat.conversation.v1.JoinConversationResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_chat_conversation_v1_conversation_proto_init() }
func file_chat_conversation_v1_conversation_proto_init() {
	if File_chat_conversation_v1_conversation_proto != nil {
		return
	}
	file_chat_conversation_v1_conversation_proto_msgTypes[2].OneofWrappers = []any{}
	file_chat_conversation_v1_conversation_proto_msgTypes[10].OneofWrappers = []any{}
	file_chat_conversation_v1_conversation_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_conversation_v1_conversation_proto_rawDesc), len(file_chat_conversation_v1_conversation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_conversation_v1_conversation_proto_goTypes,
		DependencyIndexes: file_chat_conversation_v1_conversation_proto_depIdxs,
		EnumInfos:         file_chat_conversation_v1_conversation_proto_enumTypes,
		MessageInfos:      file_chat_conversation_v1_conversation_proto_msgTypes,
	}.Build()
	File_chat_conversation_v1_conversation_proto = out.File
	file_chat_conversation_v1_conversation_proto_goTypes = nil
	file_chat_conversation_v1_conversation_proto_depIdxs = nil
}
