apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
spec:
  gatewayClassName: traefik
  listeners:
    - name: https-api
      hostname: "api.discky.com"
    - name: https-dashboard
      hostname: "traefik.discky.com"
    - name: http
      hostname: "*.discky.com"
