apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  APP_ENVIRONMENT: "production"
  ENV: "production"
  LOG_LEVEL: "info"
  JWT_PRIVATE_KEY_PATH: "/app/keys/private.pem"
  JWT_PUBLIC_KEY_PATH: "/app/keys/public.pem"
  JWT_ISSUER: "go-micro-commerce"
  KAFKA_BROKERS: "kafka-cluster-kafka-bootstrap.application.svc.cluster.local:9092"
