apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - ../../../base/fulfillment-service

labels:
  - pairs:
      environment: production
      app.kubernetes.io/managed-by: argocd

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
  - path: patch-hpa.yaml

configMapGenerator:
  - name: fulfillment-service-config
    behavior: merge
    literals:
      - ENV=production
      - LOG_LEVEL=info

images:
  - name: fulfillment-service
    newTag: latest
