package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/raphaeldiscky/go-micro-commerce/chat-service/graph"
)

// OnlineUsers is the resolver for the onlineUsers field.
func (r *queryResolver) OnlineUsers(ctx context.Context) ([]*graph.User, error) {
	_ = ctx
	// This would require integration with presence/connection service
	// For now, return empty list as this is a complex feature
	r.logger.Warn("OnlineUsers called but not fully implemented yet")

	return []*graph.User{}, nil
}
