package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/google/uuid"

	pkgconstant "github.com/raphaeldiscky/go-micro-commerce/pkg/constant"

	"github.com/raphaeldiscky/go-micro-commerce/chat-service/graph"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/constant"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/httperror"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/mapper"
)

// ConversationMessages is the resolver for the conversationMessages field.
func (r *queryResolver) ConversationMessages(
	ctx context.Context,
	conversationID string,
	first *int,
	after *string,
	last *int,
	before *string,
) (*graph.MessageConnection, error) {
	userID, ok := ctx.Value(pkgconstant.CtxKeyUserID).(uuid.UUID)
	if !ok {
		return nil, httperror.NewUnauthorizedError("user not authenticated")
	}

	convID, err := uuid.Parse(conversationID)
	if err != nil {
		return nil, httperror.NewBadRequestError("invalid conversation ID")
	}

	// Determine limit and cursors
	limit := constant.DefaultMessageLimit

	var afterCursor, beforeCursor string

	if first != nil && *first > 0 {
		limit = *first

		if after != nil {
			afterCursor = *after
		}
	} else if last != nil && *last > 0 {
		limit = *last

		if before != nil {
			beforeCursor = *before
		}
	}

	// Get messages with cursor pagination
	messages, paging, err := r.chatService.GetConversationMessagesWithCursor(
		ctx,
		convID,
		userID,
		limit,
		afterCursor,
		beforeCursor,
	)
	if err != nil {
		r.logger.Error("Failed to get conversation messages", "error", err)
		return nil, err
	}

	// Map to GraphQL MessageConnection
	return mapper.MapMessagesToCursorConnection(messages, paging), nil
}
