package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/google/uuid"
	"github.com/raphaeldiscky/go-micro-commerce/pkg/utils/echoutils"

	"github.com/raphaeldiscky/go-micro-commerce/chat-service/graph"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/constant"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/httperror"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/mapper"
)

// JoinConversation is the resolver for the joinConversation field.
func (r *mutationResolver) JoinConversation(
	ctx context.Context,
	input graph.JoinConversationInput,
) (*graph.Participant, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		r.logger.Error("Failed to get user from context", "error", err)
		return nil, err
	}

	conversationID, err := uuid.Parse(input.ConversationID)
	if err != nil {
		return nil, httperror.NewBadRequestError("invalid conversation ID")
	}

	participant, err := r.chatService.JoinConversation(
		ctx,
		conversationID,
		user.UserID,
		constant.UserTypeUser,
		input.Role,
	)
	if err != nil {
		r.logger.Error("Failed to join conversation", "error", err)
		return nil, err
	}

	return mapper.MapParticipantToGraphQL(participant), nil
}

// LeaveConversation is the resolver for the leaveConversation field.
func (r *mutationResolver) LeaveConversation(
	ctx context.Context,
	conversationID string,
) (bool, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		r.logger.Error("Failed to get user from context", "error", err)
		return false, err
	}

	convID, err := uuid.Parse(conversationID)
	if err != nil {
		return false, httperror.NewBadRequestError("invalid conversation ID")
	}

	err = r.chatService.LeaveConversation(ctx, convID, user.UserID)
	if err != nil {
		r.logger.Error("Failed to leave conversation", "error", err)
		return false, err
	}

	return true, nil
}

// ConversationParticipants is the resolver for the conversationParticipants field.
func (r *queryResolver) ConversationParticipants(
	ctx context.Context,
	conversationID string,
) ([]*graph.Participant, error) {
	convID, err := uuid.Parse(conversationID)
	if err != nil {
		return nil, httperror.NewBadRequestError("invalid conversation ID")
	}

	participants, err := r.chatService.GetConversationParticipants(ctx, convID)
	if err != nil {
		r.logger.Error("Failed to get conversation participants", "error", err)
		return nil, err
	}

	result := make([]*graph.Participant, len(participants))
	for i, p := range participants {
		result[i] = mapper.MapParticipantToGraphQL(&p)
	}

	return result, nil
}
