package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/raphaeldiscky/go-micro-commerce/pkg/utils/echoutils"

	pkgwebsocket "github.com/raphaeldiscky/go-micro-commerce/pkg/websocket"

	"github.com/raphaeldiscky/go-micro-commerce/chat-service/graph"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/constant"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/httperror"
	"github.com/raphaeldiscky/go-micro-commerce/chat-service/internal/websocket"
)

// UpdatePresence is the resolver for the updatePresence field.
func (r *mutationResolver) UpdatePresence(
	ctx context.Context,
	status constant.PresenceStatus,
) (*graph.PresenceUpdate, error) {
	// Get authenticated user from context
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		r.logger.Error("Failed to get user from context", "error", err)
		return nil, httperror.NewUnauthorizedError("authentication required")
	}

	// Create presence content
	presenceContent := websocket.PresenceContent{
		UserID: user.UserID,
		Status: status,
	}

	contentBytes, err := json.Marshal(presenceContent)
	if err != nil {
		r.logger.Error("Failed to marshal presence content", "error", err)
		return nil, httperror.NewInternalServerError("failed to process presence update")
	}

	// Create WebSocket message
	now := time.Now()
	wsMessage := &pkgwebsocket.Message{
		ID:        uuid.New(),
		Type:      websocket.ChatMessageTypePresence,
		SenderID:  &user.UserID,
		Content:   json.RawMessage(contentBytes),
		Timestamp: now,
	}

	// Publish to Redis (will broadcast to all instances)
	if err = r.messagePublisher.PublishMessage(ctx, uuid.Nil, wsMessage, nil); err != nil {
		r.logger.Error("Failed to publish presence update",
			"error", err,
			"user_id", user.UserID)

		return nil, httperror.NewInternalServerError("failed to publish presence update")
	}

	r.logger.Info("Presence update published",
		"user_id", user.UserID,
		"status", status)

	presenceEvent := &graph.PresenceUpdate{
		UserID:   user.UserID.String(),
		Status:   status,
		LastSeen: &now,
	}

	r.subscriptionManager.NotifyLocalUserSubscribers(user.UserID, presenceEvent)

	r.logger.Debug("Notified local GraphQL subscribers for presence update",
		"user_id", user.UserID)

	return presenceEvent, nil
}

// SendTypingIndicator is the resolver for the sendTypingIndicator field.
func (r *mutationResolver) SendTypingIndicator(
	ctx context.Context,
	input graph.TypingIndicatorInput,
) (*graph.TypingIndicator, error) {
	// Get authenticated user from context
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		r.logger.Error("Failed to get user from context", "error", err)
		return nil, httperror.NewUnauthorizedError("authentication required")
	}

	// Parse conversation ID
	conversationID, err := uuid.Parse(input.ConversationID)
	if err != nil {
		return nil, httperror.NewBadRequestError("invalid conversation ID")
	}

	// Create typing indicator content
	typingContent := websocket.TypingContent{
		IsTyping: input.IsTyping,
	}

	contentBytes, err := json.Marshal(typingContent)
	if err != nil {
		r.logger.Error("Failed to marshal typing content", "error", err)
		return nil, httperror.NewInternalServerError("failed to process typing indicator")
	}

	// Create WebSocket message
	now := time.Now()
	channelName := websocket.ConversationChannel(conversationID)
	wsMessage := &pkgwebsocket.Message{
		ID:        uuid.New(),
		Type:      websocket.ChatMessageTypeTyping,
		Channel:   &channelName,
		SenderID:  &user.UserID,
		Content:   json.RawMessage(contentBytes),
		Timestamp: now,
	}

	// Publish to Redis (will broadcast to all instances)
	if err = r.messagePublisher.PublishMessage(ctx, conversationID, wsMessage, &user.UserID); err != nil {
		r.logger.Error("Failed to publish typing indicator",
			"error", err,
			"user_id", user.UserID,
			"conversation_id", conversationID)

		return nil, httperror.NewInternalServerError("failed to publish typing indicator")
	}

	r.logger.Info("Typing indicator published",
		"user_id", user.UserID,
		"conversation_id", conversationID,
		"is_typing", input.IsTyping)

	typingEvent := &graph.TypingIndicator{
		UserID:         user.UserID.String(),
		ConversationID: input.ConversationID,
		IsTyping:       input.IsTyping,
		Timestamp:      now,
	}

	r.subscriptionManager.NotifyLocalConversationSubscribers(conversationID, typingEvent)

	r.logger.Debug("Notified local GraphQL subscribers for typing indicator",
		"user_id", user.UserID,
		"conversation_id", conversationID)

	return typingEvent, nil
}

// ConversationEvents is the resolver for the conversationEvents field.
func (r *subscriptionResolver) ConversationEvents(
	ctx context.Context,
	conversationID string,
) (<-chan graph.ConversationEvent, error) {
	r.logger.Info("🔔 GraphQL subscription request received",
		"conversation_id", conversationID)

	// Validate conversation ID
	convID, err := uuid.Parse(conversationID)
	if err != nil {
		r.logger.Error("Invalid conversation ID in subscription",
			"error", err,
			"conversation_id", conversationID)

		return nil, httperror.NewBadRequestError("invalid conversation ID")
	}

	// Subscribe to conversation events via the manager
	eventChan, err := r.subscriptionManager.SubscribeToConversation(ctx, convID)
	if err != nil {
		r.logger.Error("Failed to subscribe to conversation events",
			"error", err,
			"conversation_id", conversationID)

		return nil, err
	}

	r.logger.Info("✅ GraphQL subscription established",
		"conversation_id", conversationID,
		"channel_buffer", cap(eventChan))

	return eventChan, nil
}

// UserEvents is the resolver for the userEvents field.
func (r *subscriptionResolver) UserEvents(ctx context.Context) (<-chan graph.UserEvent, error) {
	user, err := echoutils.GetUserAuthContexts(ctx)
	if err != nil {
		r.logger.Error("Failed to get user from context", "error", err)
		return nil, err
	}

	// Subscribe to user events via the manager
	eventChan, err := r.subscriptionManager.SubscribeToUserEvents(ctx, user.UserID)
	if err != nil {
		r.logger.Error("Failed to subscribe to user events",
			"error", err,
			"user_id", user.UserID)

		return nil, err
	}

	r.logger.Info("GraphQL subscription started for user events",
		"user_id", user.UserID)

	return eventChan, nil
}

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
