apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-git-credentials
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: repo-credentials
    app.kubernetes.io/managed-by: external-secrets
    app.kubernetes.io/part-of: go-micro-commerce
    environment: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: git-repo-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:raphaeldiscky/go-micro-commerce.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd-git-ssh-private-key
