apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      type: Opaque
      engineVersion: v2
      data:
        admin.password: "{{ .adminPassword | bcrypt }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: argocd-admin-password
