apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fulfillment-pg-credentials
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: fulfillment-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: fulfillment-pg-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        username: "fulfillment_user"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: fulfillment-pg-password
