apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secrets
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        admin-password: "{{ .adminPassword }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: grafana-admin-password
