apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - auth-service-external-secret.yaml
  - payment-service-external-secret.yaml
  - notification-service-external-secret.yaml
  - search-service-external-secret.yaml
  - order-service-external-secret.yaml
  - redis-external-secret.yaml
  - chat-service-external-secret.yaml
  - grafana-external-secret.yaml
  - argocd-external-secret.yaml
  - ghcr-imagepull-secret.yaml
  - ghcr-imagepull-secret-gateway.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: go-micro-commerce
      app.kubernetes.io/managed-by: external-secrets
