apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-service-external-secret.yaml
  - payment-service-external-secret.yaml
  - notification-service-external-secret.yaml
  - redis-external-secret.yaml
  - chat-service-external-secret.yaml
  - grafana-external-secret.yaml
  - argocd-external-secret.yaml
  - argocd-git-credentials-external-secret.yaml
  - ghcr-imagepull-secret.yaml
  - ghcr-imagepull-secret-gateway.yaml
  - ghcr-imagepull-secret-graphql.yaml
  - traefik-dashboard-external-secret.yaml
  # PostgreSQL service credentials
  - auth-pg-external-secret.yaml
  - cart-pg-external-secret.yaml
  - chat-pg-external-secret.yaml
  - fulfillment-pg-external-secret.yaml
  - notification-pg-external-secret.yaml
  - order-pg-external-secret.yaml
  - payment-pg-external-secret.yaml
  - product-pg-external-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: go-micro-commerce
      app.kubernetes.io/managed-by: external-secrets
