apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: notification-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        MAIL_SENDGRID_API_KEY: "{{ .sendgridApiKey }}"
  data:
    - secretKey: sendgridApiKey
      remoteRef:
        key: notification-service-sendgrid-api-key
