apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-service-secrets
  namespace: default
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: order-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        TEMPORAL_API_KEY: "{{ .temporalApiKey }}"
  data:
    - secretKey: temporalApiKey
      remoteRef:
        key: order-service-temporal-api-key
