apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-pg-credentials
  namespace: application
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: order-pg-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        username: "order_user"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: order-pg-password
