apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-cluster-secrets
  namespace: default
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: redis-cluster-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ .redisPassword }}"
  data:
    - secretKey: redisPassword
      remoteRef:
        key: redis-cluster-password
