apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: search-service-secrets
  namespace: application
  labels:
    app.kubernetes.io/name: search-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: search-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        ELASTICSEARCH_USERNAME: "{{ .elasticsearchUsername }}"
        ELASTICSEARCH_PASSWORD: "{{ .elasticsearchPassword }}"
  data:
    - secretKey: elasticsearchUsername
      remoteRef:
        key: search-service-elasticsearch-username
    - secretKey: elasticsearchPassword
      remoteRef:
        key: search-service-elasticsearch-password
